# Исследование надежности заемщиков
Проект по исследованию влияния семейного положения и количества детей клиента на факт погашения кредита в срок для построения модели кредитного скоринга.

**Статус проекта:** ✅завершен, проверен ревьюером.

<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Постановка-задачи" data-toc-modified-id="Постановка-задачи-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Постановка задачи</a></span></li><li><span><a href="#Резюме-проекта" data-toc-modified-id="Резюме-проекта-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Резюме проекта</a></span></li><li><span><a href="#Краткое-содержание-работы" data-toc-modified-id="Краткое-содержание-работы-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Краткое содержание работы</a></span></li><li><span><a href="#Обзор-данных" data-toc-modified-id="Обзор-данных-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Обзор данных</a></span><ul class="toc-item"><li><span><a href="#Импорт-библиотек-и-данных" data-toc-modified-id="Импорт-библиотек-и-данных-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Импорт библиотек и данных</a></span></li><li><span><a href="#Обзор-датасета" data-toc-modified-id="Обзор-датасета-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Обзор датасета</a></span></li><li><span><a href="#Выводы-по-разделу-4" data-toc-modified-id="Выводы-по-разделу-4-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>Выводы по разделу 4</a></span></li></ul></li><li><span><a href="#Предобработка-данных" data-toc-modified-id="Предобработка-данных-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Предобработка данных</a></span><ul class="toc-item"><li><span><a href="#Заполнение-пропусков" data-toc-modified-id="Заполнение-пропусков-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>Заполнение пропусков</a></span><ul class="toc-item"><li><span><a href="#Нахождение-пропусков" data-toc-modified-id="Нахождение-пропусков-5.1.1"><span class="toc-item-num">5.1.1&nbsp;&nbsp;</span>Нахождение пропусков</a></span></li><li><span><a href="#Изучение-пропусков" data-toc-modified-id="Изучение-пропусков-5.1.2"><span class="toc-item-num">5.1.2&nbsp;&nbsp;</span>Изучение пропусков</a></span></li><li><span><a href="#Заполнение-пропусков-в-столбце-total_income" data-toc-modified-id="Заполнение-пропусков-в-столбце-total_income-5.1.3"><span class="toc-item-num">5.1.3&nbsp;&nbsp;</span>Заполнение пропусков в столбце <code>total_income</code></a></span><ul class="toc-item"><li><span><a href="#Получение-уникальных-значений-в-столбце-income_type" data-toc-modified-id="Получение-уникальных-значений-в-столбце-income_type-5.1.3.1"><span class="toc-item-num">5.1.3.1&nbsp;&nbsp;</span>Получение уникальных значений в столбце <code>income_type</code></a></span></li><li><span><a href="#Нахождение-медианных-значений-в-столбце-total_income-в-зависимости-от-значения-в-столбце-income_type" data-toc-modified-id="Нахождение-медианных-значений-в-столбце-total_income-в-зависимости-от-значения-в-столбце-income_type-5.1.3.2"><span class="toc-item-num">5.1.3.2&nbsp;&nbsp;</span>Нахождение медианных значений в столбце <code>total_income</code> в зависимости от значения в столбце <code>income_type</code></a></span></li><li><span><a href="#Заполнение-пропусков.-Вариант-1-(первоначальный)" data-toc-modified-id="Заполнение-пропусков.-Вариант-1-(первоначальный)-5.1.3.3"><span class="toc-item-num">5.1.3.3&nbsp;&nbsp;</span>Заполнение пропусков. Вариант 1 (первоначальный)</a></span></li><li><span><a href="#Заполнение-пропусков.-Вариант-2-(после-ревью)" data-toc-modified-id="Заполнение-пропусков.-Вариант-2-(после-ревью)-5.1.3.4"><span class="toc-item-num">5.1.3.4&nbsp;&nbsp;</span>Заполнение пропусков. Вариант 2 (после ревью)</a></span></li><li><span><a href="#Заполнение-пропусков.-Вариант-3-(после-прохождения-курса)" data-toc-modified-id="Заполнение-пропусков.-Вариант-3-(после-прохождения-курса)-5.1.3.5"><span class="toc-item-num">5.1.3.5&nbsp;&nbsp;</span>Заполнение пропусков. Вариант 3 (после прохождения курса)</a></span></li><li><span><a href="#Проверка-заполнения-пропусков" data-toc-modified-id="Проверка-заполнения-пропусков-5.1.3.6"><span class="toc-item-num">5.1.3.6&nbsp;&nbsp;</span>Проверка заполнения пропусков</a></span></li></ul></li><li><span><a href="#Вывод-по-подразделу-5.1" data-toc-modified-id="Вывод-по-подразделу-5.1-5.1.4"><span class="toc-item-num">5.1.4&nbsp;&nbsp;</span>Вывод по подразделу 5.1</a></span></li></ul></li><li><span><a href="#Проверка-данных-на-аномалии-и-исправления" data-toc-modified-id="Проверка-данных-на-аномалии-и-исправления-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>Проверка данных на аномалии и исправления</a></span><ul class="toc-item"><li><span><a href="#Проверка-столбца-children" data-toc-modified-id="Проверка-столбца-children-5.2.1"><span class="toc-item-num">5.2.1&nbsp;&nbsp;</span>Проверка столбца <code>children</code></a></span><ul class="toc-item"><li><span><a href="#Поиск-аномальных-значений-в-столбце-children" data-toc-modified-id="Поиск-аномальных-значений-в-столбце-children-5.2.1.1"><span class="toc-item-num">5.2.1.1&nbsp;&nbsp;</span>Поиск аномальных значений в столбце <code>children</code></a></span></li><li><span><a href="#Анализ-аномальных-значений-в-столбце-children" data-toc-modified-id="Анализ-аномальных-значений-в-столбце-children-5.2.1.2"><span class="toc-item-num">5.2.1.2&nbsp;&nbsp;</span>Анализ аномальных значений в столбце <code>children</code></a></span></li><li><span><a href="#Исправление-аномальных-значений--в-столбце-children" data-toc-modified-id="Исправление-аномальных-значений--в-столбце-children-5.2.1.3"><span class="toc-item-num">5.2.1.3&nbsp;&nbsp;</span>Исправление аномальных значений  в столбце <code>children</code></a></span></li><li><span><a href="#Проверка-исправления-аномальных-значений--в-столбце-children" data-toc-modified-id="Проверка-исправления-аномальных-значений--в-столбце-children-5.2.1.4"><span class="toc-item-num">5.2.1.4&nbsp;&nbsp;</span>Проверка исправления аномальных значений  в столбце <code>children</code></a></span></li><li><span><a href="#Вывод-по-подразделу-5.2.1" data-toc-modified-id="Вывод-по-подразделу-5.2.1-5.2.1.5"><span class="toc-item-num">5.2.1.5&nbsp;&nbsp;</span>Вывод по подразделу 5.2.1</a></span></li></ul></li><li><span><a href="#Проверка-столбца-days_employed" data-toc-modified-id="Проверка-столбца-days_employed-5.2.2"><span class="toc-item-num">5.2.2&nbsp;&nbsp;</span>Проверка столбца <code>days_employed</code></a></span><ul class="toc-item"><li><span><a href="#Поиск-аномальных-значений-в-столбце-days_employed" data-toc-modified-id="Поиск-аномальных-значений-в-столбце-days_employed-5.2.2.1"><span class="toc-item-num">5.2.2.1&nbsp;&nbsp;</span>Поиск аномальных значений в столбце <code>days_employed</code></a></span></li><li><span><a href="#Анализ-аномальных-значений-в-столбце-days_employed" data-toc-modified-id="Анализ-аномальных-значений-в-столбце-days_employed-5.2.2.2"><span class="toc-item-num">5.2.2.2&nbsp;&nbsp;</span>Анализ аномальных значений в столбце <code>days_employed</code></a></span></li><li><span><a href="#Исправление-аномальных-значений-в-столбце-days_employed" data-toc-modified-id="Исправление-аномальных-значений-в-столбце-days_employed-5.2.2.3"><span class="toc-item-num">5.2.2.3&nbsp;&nbsp;</span>Исправление аномальных значений в столбце <code>days_employed</code></a></span></li><li><span><a href="#Вывод-по-подразделу-5.2.2" data-toc-modified-id="Вывод-по-подразделу-5.2.2-5.2.2.4"><span class="toc-item-num">5.2.2.4&nbsp;&nbsp;</span>Вывод по подразделу 5.2.2</a></span></li></ul></li><li><span><a href="#Проверка-столбца-dob_years" data-toc-modified-id="Проверка-столбца-dob_years-5.2.3"><span class="toc-item-num">5.2.3&nbsp;&nbsp;</span>Проверка столбца <code>dob_years</code></a></span><ul class="toc-item"><li><span><a href="#Поиск-аномальных-значений-в-столбце-dob_years" data-toc-modified-id="Поиск-аномальных-значений-в-столбце-dob_years-5.2.3.1"><span class="toc-item-num">5.2.3.1&nbsp;&nbsp;</span>Поиск аномальных значений в столбце <code>dob_years</code></a></span></li><li><span><a href="#Анализ-аномальных-значений-в-столбце-dob_years" data-toc-modified-id="Анализ-аномальных-значений-в-столбце-dob_years-5.2.3.2"><span class="toc-item-num">5.2.3.2&nbsp;&nbsp;</span>Анализ аномальных значений в столбце <code>dob_years</code></a></span></li><li><span><a href="#Исправление-аномальных-значений-в-столбце-dob_years" data-toc-modified-id="Исправление-аномальных-значений-в-столбце-dob_years-5.2.3.3"><span class="toc-item-num">5.2.3.3&nbsp;&nbsp;</span>Исправление аномальных значений в столбце <code>dob_years</code></a></span></li><li><span><a href="#Вывод-по-подразделу-5.2.3" data-toc-modified-id="Вывод-по-подразделу-5.2.3-5.2.3.4"><span class="toc-item-num">5.2.3.4&nbsp;&nbsp;</span>Вывод по подразделу 5.2.3</a></span></li></ul></li><li><span><a href="#Проверка-столбца-education" data-toc-modified-id="Проверка-столбца-education-5.2.4"><span class="toc-item-num">5.2.4&nbsp;&nbsp;</span>Проверка столбца <code>education</code></a></span><ul class="toc-item"><li><span><a href="#Поиск-аномальных-значений-в-столбце-education" data-toc-modified-id="Поиск-аномальных-значений-в-столбце-education-5.2.4.1"><span class="toc-item-num">5.2.4.1&nbsp;&nbsp;</span>Поиск аномальных значений в столбце <code>education</code></a></span></li><li><span><a href="#Исправление-аномальных-значений-в-столбце-education" data-toc-modified-id="Исправление-аномальных-значений-в-столбце-education-5.2.4.2"><span class="toc-item-num">5.2.4.2&nbsp;&nbsp;</span>Исправление аномальных значений в столбце <code>education</code></a></span></li><li><span><a href="#Вывод-по-подразделу-5.2.4" data-toc-modified-id="Вывод-по-подразделу-5.2.4-5.2.4.3"><span class="toc-item-num">5.2.4.3&nbsp;&nbsp;</span>Вывод по подразделу 5.2.4</a></span></li></ul></li><li><span><a href="#Проверка-столбца-education_id" data-toc-modified-id="Проверка-столбца-education_id-5.2.5"><span class="toc-item-num">5.2.5&nbsp;&nbsp;</span>Проверка столбца <code>education_id</code></a></span><ul class="toc-item"><li><span><a href="#Поиск-аномальных-значений-в-столбце-education_id" data-toc-modified-id="Поиск-аномальных-значений-в-столбце-education_id-5.2.5.1"><span class="toc-item-num">5.2.5.1&nbsp;&nbsp;</span>Поиск аномальных значений в столбце <code>education_id</code></a></span></li><li><span><a href="#Выводы-по-подразделу-5.2.5" data-toc-modified-id="Выводы-по-подразделу-5.2.5-5.2.5.2"><span class="toc-item-num">5.2.5.2&nbsp;&nbsp;</span>Выводы по подразделу 5.2.5</a></span></li></ul></li><li><span><a href="#Проверка-столбца-family_status" data-toc-modified-id="Проверка-столбца-family_status-5.2.6"><span class="toc-item-num">5.2.6&nbsp;&nbsp;</span>Проверка столбца <code>family_status</code></a></span><ul class="toc-item"><li><span><a href="#Поиск-аномальных-значений-в-столбце-family_status" data-toc-modified-id="Поиск-аномальных-значений-в-столбце-family_status-5.2.6.1"><span class="toc-item-num">5.2.6.1&nbsp;&nbsp;</span>Поиск аномальных значений в столбце <code>family_status</code></a></span></li><li><span><a href="#Исправление-аномальных-значений-в-столбце-family_status" data-toc-modified-id="Исправление-аномальных-значений-в-столбце-family_status-5.2.6.2"><span class="toc-item-num">5.2.6.2&nbsp;&nbsp;</span>Исправление аномальных значений в столбце <code>family_status</code></a></span></li><li><span><a href="#Вывод-по-подразделу-5.2.6" data-toc-modified-id="Вывод-по-подразделу-5.2.6-5.2.6.3"><span class="toc-item-num">5.2.6.3&nbsp;&nbsp;</span>Вывод по подразделу 5.2.6</a></span></li></ul></li><li><span><a href="#Проверка-столбца-family_status_id" data-toc-modified-id="Проверка-столбца-family_status_id-5.2.7"><span class="toc-item-num">5.2.7&nbsp;&nbsp;</span>Проверка столбца <code>family_status_id</code></a></span><ul class="toc-item"><li><span><a href="#Поиск-аномальных-значений-в-столбце-family_status_id" data-toc-modified-id="Поиск-аномальных-значений-в-столбце-family_status_id-5.2.7.1"><span class="toc-item-num">5.2.7.1&nbsp;&nbsp;</span>Поиск аномальных значений в столбце <code>family_status_id</code></a></span></li><li><span><a href="#Выводы-по-подразделу-5.2.7" data-toc-modified-id="Выводы-по-подразделу-5.2.7-5.2.7.2"><span class="toc-item-num">5.2.7.2&nbsp;&nbsp;</span>Выводы по подразделу 5.2.7</a></span></li></ul></li><li><span><a href="#Проверка-столбца-gender" data-toc-modified-id="Проверка-столбца-gender-5.2.8"><span class="toc-item-num">5.2.8&nbsp;&nbsp;</span>Проверка столбца <code>gender</code></a></span><ul class="toc-item"><li><span><a href="#Поиск-аномальных-значений-в-столбце-gender" data-toc-modified-id="Поиск-аномальных-значений-в-столбце-gender-5.2.8.1"><span class="toc-item-num">5.2.8.1&nbsp;&nbsp;</span>Поиск аномальных значений в столбце <code>gender</code></a></span></li><li><span><a href="#Анализ-аномальных-значений-в-столбце-gender" data-toc-modified-id="Анализ-аномальных-значений-в-столбце-gender-5.2.8.2"><span class="toc-item-num">5.2.8.2&nbsp;&nbsp;</span>Анализ аномальных значений в столбце <code>gender</code></a></span></li><li><span><a href="#Исправление-аномальных-значений-в-столбце-gender" data-toc-modified-id="Исправление-аномальных-значений-в-столбце-gender-5.2.8.3"><span class="toc-item-num">5.2.8.3&nbsp;&nbsp;</span>Исправление аномальных значений в столбце <code>gender</code></a></span></li><li><span><a href="#Выводы-по-подразделу-5.2.8" data-toc-modified-id="Выводы-по-подразделу-5.2.8-5.2.8.4"><span class="toc-item-num">5.2.8.4&nbsp;&nbsp;</span>Выводы по подразделу 5.2.8</a></span></li></ul></li><li><span><a href="#Проверка-столбца-income_type" data-toc-modified-id="Проверка-столбца-income_type-5.2.9"><span class="toc-item-num">5.2.9&nbsp;&nbsp;</span>Проверка столбца <code>income_type</code></a></span><ul class="toc-item"><li><span><a href="#Поиск-аномальных-значений-в-столбце-income_type" data-toc-modified-id="Поиск-аномальных-значений-в-столбце-income_type-5.2.9.1"><span class="toc-item-num">5.2.9.1&nbsp;&nbsp;</span>Поиск аномальных значений в столбце <code>income_type</code></a></span></li><li><span><a href="#Выводы-по-подразделу-5.2.9" data-toc-modified-id="Выводы-по-подразделу-5.2.9-5.2.9.2"><span class="toc-item-num">5.2.9.2&nbsp;&nbsp;</span>Выводы по подразделу 5.2.9</a></span></li></ul></li><li><span><a href="#Проверка-столбца-debt" data-toc-modified-id="Проверка-столбца-debt-5.2.10"><span class="toc-item-num">5.2.10&nbsp;&nbsp;</span>Проверка столбца <code>debt</code></a></span><ul class="toc-item"><li><span><a href="#Поиск-аномальных-значений-в-столбце-debt" data-toc-modified-id="Поиск-аномальных-значений-в-столбце-debt-5.2.10.1"><span class="toc-item-num">5.2.10.1&nbsp;&nbsp;</span>Поиск аномальных значений в столбце <code>debt</code></a></span></li><li><span><a href="#Вывод-по-подразделу-5.2.10" data-toc-modified-id="Вывод-по-подразделу-5.2.10-5.2.10.2"><span class="toc-item-num">5.2.10.2&nbsp;&nbsp;</span>Вывод по подразделу 5.2.10</a></span></li></ul></li><li><span><a href="#Проверка-столбца-total_income" data-toc-modified-id="Проверка-столбца-total_income-5.2.11"><span class="toc-item-num">5.2.11&nbsp;&nbsp;</span>Проверка столбца <code>total_income</code></a></span><ul class="toc-item"><li><span><a href="#Поиск-аномальных-значений-в-столбце-total_income" data-toc-modified-id="Поиск-аномальных-значений-в-столбце-total_income-5.2.11.1"><span class="toc-item-num">5.2.11.1&nbsp;&nbsp;</span>Поиск аномальных значений в столбце <code>total_income</code></a></span></li><li><span><a href="#Вывод-по-подразделу-5.2.11" data-toc-modified-id="Вывод-по-подразделу-5.2.11-5.2.11.2"><span class="toc-item-num">5.2.11.2&nbsp;&nbsp;</span>Вывод по подразделу 5.2.11</a></span></li></ul></li><li><span><a href="#Проверка-столбца-purpose" data-toc-modified-id="Проверка-столбца-purpose-5.2.12"><span class="toc-item-num">5.2.12&nbsp;&nbsp;</span>Проверка столбца <code>purpose</code></a></span><ul class="toc-item"><li><span><a href="#Поиск-аномальных-значений-в-столбце-purpose" data-toc-modified-id="Поиск-аномальных-значений-в-столбце-purpose-5.2.12.1"><span class="toc-item-num">5.2.12.1&nbsp;&nbsp;</span>Поиск аномальных значений в столбце <code>purpose</code></a></span></li><li><span><a href="#Выводы-по-подразделу-5.2.12" data-toc-modified-id="Выводы-по-подразделу-5.2.12-5.2.12.2"><span class="toc-item-num">5.2.12.2&nbsp;&nbsp;</span>Выводы по подразделу 5.2.12</a></span></li></ul></li></ul></li><li><span><a href="#Изменение-типов-данных" data-toc-modified-id="Изменение-типов-данных-5.3"><span class="toc-item-num">5.3&nbsp;&nbsp;</span>Изменение типов данных</a></span><ul class="toc-item"><li><span><a href="#Замена-типа-данных-в-столбце-total_income" data-toc-modified-id="Замена-типа-данных-в-столбце-total_income-5.3.1"><span class="toc-item-num">5.3.1&nbsp;&nbsp;</span>Замена типа данных в столбце <code>total_income</code></a></span></li><li><span><a href="#Вывод-по-подразделу-5.3" data-toc-modified-id="Вывод-по-подразделу-5.3-5.3.2"><span class="toc-item-num">5.3.2&nbsp;&nbsp;</span>Вывод по подразделу 5.3</a></span></li></ul></li><li><span><a href="#Удаление-строк-дубликатов-в-данных" data-toc-modified-id="Удаление-строк-дубликатов-в-данных-5.4"><span class="toc-item-num">5.4&nbsp;&nbsp;</span>Удаление строк-дубликатов в данных</a></span><ul class="toc-item"><li><span><a href="#Поиск-строк-дубликатов-в-данных" data-toc-modified-id="Поиск-строк-дубликатов-в-данных-5.4.1"><span class="toc-item-num">5.4.1&nbsp;&nbsp;</span>Поиск строк-дубликатов в данных</a></span></li><li><span><a href="#Удаление-строк-дубликатов-в-данных" data-toc-modified-id="Удаление-строк-дубликатов-в-данных-5.4.2"><span class="toc-item-num">5.4.2&nbsp;&nbsp;</span>Удаление строк-дубликатов в данных</a></span></li><li><span><a href="#Вывод-по-подразделу-5.4" data-toc-modified-id="Вывод-по-подразделу-5.4-5.4.3"><span class="toc-item-num">5.4.3&nbsp;&nbsp;</span>Вывод по подразделу 5.4</a></span></li></ul></li><li><span><a href="#Декомпозиция-исходного-датафрейма.-Формирование-дополнительных-датафреймов-словарей" data-toc-modified-id="Декомпозиция-исходного-датафрейма.-Формирование-дополнительных-датафреймов-словарей-5.5"><span class="toc-item-num">5.5&nbsp;&nbsp;</span>Декомпозиция исходного датафрейма. Формирование дополнительных датафреймов словарей</a></span><ul class="toc-item"><li><span><a href="#Уточнение-значений-категорий-содержащихся-в-столбцах-education-и-family_status" data-toc-modified-id="Уточнение-значений-категорий-содержащихся-в-столбцах-education-и-family_status-5.5.1"><span class="toc-item-num">5.5.1&nbsp;&nbsp;</span>Уточнение значений категорий содержащихся в столбцах <code>education</code> и <code>family_status</code></a></span></li><li><span><a href="#Создание-датафреймов-&quot;словарей&quot;-для-хранения-категорий-education-и-family_status" data-toc-modified-id="Создание-датафреймов-&quot;словарей&quot;-для-хранения-категорий-education-и-family_status-5.5.2"><span class="toc-item-num">5.5.2&nbsp;&nbsp;</span>Создание датафреймов "словарей" для хранения категорий <code>education</code> и <code>family_status</code></a></span></li><li><span><a href="#Удаление-столбцов-education-и-family_status-из-исходного-датафрейма" data-toc-modified-id="Удаление-столбцов-education-и-family_status-из-исходного-датафрейма-5.5.3"><span class="toc-item-num">5.5.3&nbsp;&nbsp;</span>Удаление столбцов <code>education</code> и <code>family_status</code> из исходного датафрейма</a></span></li><li><span><a href="#Вывод-по-подразделу-5.5" data-toc-modified-id="Вывод-по-подразделу-5.5-5.5.4"><span class="toc-item-num">5.5.4&nbsp;&nbsp;</span>Вывод по подразделу 5.5</a></span></li></ul></li><li><span><a href="#Категоризация-дохода" data-toc-modified-id="Категоризация-дохода-5.6"><span class="toc-item-num">5.6&nbsp;&nbsp;</span>Категоризация дохода</a></span><ul class="toc-item"><li><span><a href="#Создание-функции-set_income_category" data-toc-modified-id="Создание-функции-set_income_category-5.6.1"><span class="toc-item-num">5.6.1&nbsp;&nbsp;</span>Создание функции <code>set_income_category</code></a></span></li><li><span><a href="#Добавление-в-датафрейм-столбца-с-категорией-дохода" data-toc-modified-id="Добавление-в-датафрейм-столбца-с-категорией-дохода-5.6.2"><span class="toc-item-num">5.6.2&nbsp;&nbsp;</span>Добавление в датафрейм столбца с категорией дохода</a></span></li><li><span><a href="#Вывод-по-подразделу-5.6" data-toc-modified-id="Вывод-по-подразделу-5.6-5.6.3"><span class="toc-item-num">5.6.3&nbsp;&nbsp;</span>Вывод по подразделу 5.6</a></span></li></ul></li><li><span><a href="#Категоризация-целей-кредита" data-toc-modified-id="Категоризация-целей-кредита-5.7"><span class="toc-item-num">5.7&nbsp;&nbsp;</span>Категоризация целей кредита</a></span><ul class="toc-item"><li><span><a href="#Изучение-столбца-purpose-и-выделение-подстрок-для-определения-категории" data-toc-modified-id="Изучение-столбца-purpose-и-выделение-подстрок-для-определения-категории-5.7.1"><span class="toc-item-num">5.7.1&nbsp;&nbsp;</span>Изучение столбца <code>purpose</code> и выделение подстрок для определения категории</a></span></li><li><span><a href="#Функция-для-категоризации-целей-кредитования-по-ключевым-словам" data-toc-modified-id="Функция-для-категоризации-целей-кредитования-по-ключевым-словам-5.7.2"><span class="toc-item-num">5.7.2&nbsp;&nbsp;</span>Функция для категоризации целей кредитования по ключевым словам</a></span></li><li><span><a href="#Категоризация-датафрейма-по-целям-кредитования" data-toc-modified-id="Категоризация-датафрейма-по-целям-кредитования-5.7.3"><span class="toc-item-num">5.7.3&nbsp;&nbsp;</span>Категоризация датафрейма по целям кредитования</a></span></li><li><span><a href="#Вывод-по-подразделу-5.7" data-toc-modified-id="Вывод-по-подразделу-5.7-5.7.4"><span class="toc-item-num">5.7.4&nbsp;&nbsp;</span>Вывод по подразделу 5.7</a></span></li></ul></li></ul></li><li><span><a href="#Ответы-на-вопросы" data-toc-modified-id="Ответы-на-вопросы-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Ответы на вопросы</a></span><ul class="toc-item"><li><span><a href="#Вопрос-1" data-toc-modified-id="Вопрос-1-6.1"><span class="toc-item-num">6.1&nbsp;&nbsp;</span>Вопрос 1</a></span><ul class="toc-item"><li><span><a href="#Вариант-1-(первоначальный,-после-ревью)" data-toc-modified-id="Вариант-1-(первоначальный,-после-ревью)-6.1.1"><span class="toc-item-num">6.1.1&nbsp;&nbsp;</span>Вариант 1 (первоначальный, после ревью)</a></span></li><li><span><a href="#Вариант-2-(после-прохождения-курса)" data-toc-modified-id="Вариант-2-(после-прохождения-курса)-6.1.2"><span class="toc-item-num">6.1.2&nbsp;&nbsp;</span>Вариант 2 (после прохождения курса)</a></span></li><li><span><a href="#Ответ-на-вопрос-1" data-toc-modified-id="Ответ-на-вопрос-1-6.1.3"><span class="toc-item-num">6.1.3&nbsp;&nbsp;</span>Ответ на вопрос 1</a></span></li></ul></li><li><span><a href="#Вопрос-2" data-toc-modified-id="Вопрос-2-6.2"><span class="toc-item-num">6.2&nbsp;&nbsp;</span>Вопрос 2</a></span><ul class="toc-item"><li><span><a href="#Вариант-1-(первоначальный,-после-ревью)" data-toc-modified-id="Вариант-1-(первоначальный,-после-ревью)-6.2.1"><span class="toc-item-num">6.2.1&nbsp;&nbsp;</span>Вариант 1 (первоначальный, после ревью)</a></span></li><li><span><a href="#Вариант-2-(после-прохождения-курса)" data-toc-modified-id="Вариант-2-(после-прохождения-курса)-6.2.2"><span class="toc-item-num">6.2.2&nbsp;&nbsp;</span>Вариант 2 (после прохождения курса)</a></span></li><li><span><a href="#Ответ-на-вопрос-2" data-toc-modified-id="Ответ-на-вопрос-2-6.2.3"><span class="toc-item-num">6.2.3&nbsp;&nbsp;</span>Ответ на вопрос 2</a></span></li></ul></li><li><span><a href="#Вопрос-3" data-toc-modified-id="Вопрос-3-6.3"><span class="toc-item-num">6.3&nbsp;&nbsp;</span>Вопрос 3</a></span><ul class="toc-item"><li><span><a href="#Вариант-1-(первоначальный,-после-ревью)" data-toc-modified-id="Вариант-1-(первоначальный,-после-ревью)-6.3.1"><span class="toc-item-num">6.3.1&nbsp;&nbsp;</span>Вариант 1 (первоначальный, после ревью)</a></span></li><li><span><a href="#Вариант-2-(после-прохождения-курса)" data-toc-modified-id="Вариант-2-(после-прохождения-курса)-6.3.2"><span class="toc-item-num">6.3.2&nbsp;&nbsp;</span>Вариант 2 (после прохождения курса)</a></span></li><li><span><a href="#Ответ-на-вопрос-3" data-toc-modified-id="Ответ-на-вопрос-3-6.3.3"><span class="toc-item-num">6.3.3&nbsp;&nbsp;</span>Ответ на вопрос 3</a></span></li></ul></li><li><span><a href="#Вопрос-4" data-toc-modified-id="Вопрос-4-6.4"><span class="toc-item-num">6.4&nbsp;&nbsp;</span>Вопрос 4</a></span><ul class="toc-item"><li><span><a href="#Вариант-1-(первоначальный,-после-ревью)" data-toc-modified-id="Вариант-1-(первоначальный,-после-ревью)-6.4.1"><span class="toc-item-num">6.4.1&nbsp;&nbsp;</span>Вариант 1 (первоначальный, после ревью)</a></span></li><li><span><a href="#Вариант-2-(после-прохождения-курса)" data-toc-modified-id="Вариант-2-(после-прохождения-курса)-6.4.2"><span class="toc-item-num">6.4.2&nbsp;&nbsp;</span>Вариант 2 (после прохождения курса)</a></span></li></ul></li><li><span><a href="#Причины-появления-пропусков-в-исходных-данных" data-toc-modified-id="Причины-появления-пропусков-в-исходных-данных-6.5"><span class="toc-item-num">6.5&nbsp;&nbsp;</span>Причины появления пропусков в исходных данных</a></span></li><li><span><a href="#Обоснование-заполнения-пропусков-медианным-значением" data-toc-modified-id="Обоснование-заполнения-пропусков-медианным-значением-6.6"><span class="toc-item-num">6.6&nbsp;&nbsp;</span>Обоснование заполнения пропусков медианным значением</a></span></li></ul></li><li><span><a href="#Общий-вывод" data-toc-modified-id="Общий-вывод-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Общий вывод</a></span></li><li><span><a href="#Чек-лист-выполнения-проекта" data-toc-modified-id="Чек-лист-выполнения-проекта-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Чек-лист выполнения проекта</a></span></li></ul></div>

## Постановка задачи

Кредитный отдел банка хочет разобраться, влияет ли семейное положение и количество детей клиента на факт погашения кредита в срок.

**Цель исследования** — на основе предоставленной банком статистики о платежеспособности клиентов проанализировать влияние таких факторов как семейное положение и количество детей на риск непогашения клиентом кредита в срок.

**Задача исследования** — дать ответы на следующие вопросы:
* Есть ли зависимость между количеством детей и возвратом кредита в срок?
* Есть ли зависимость между семейным положением и возвратом кредита в срок?
* Есть ли зависимость между уровнем дохода и возвратом кредита в срок?
* Как разные цели кредита влияют на его возврат в срок?

Ответы должны быть сопровождены интерпретацией — о чём именно говорит полученный результат.

Результаты исследования будут учтены при построении модели кредитного скоринга — специальной системы, которая оценивает способность потенциального заёмщика вернуть кредит банку.

**Источник данных:** файл `data.csv` — предоставленные банком данные со статистикой платежеспособности клиентов

Описание колонок:
- `children` — количество детей в семье;
- `days_employed` — общий трудовой стаж в днях;
- `dob_years` — возраст клиента в годах;
- `education` — уровень образования клиента;
- `education_id` — идентификатор уровня образования;
- `family_status` — семейное положение;
- `family_status_id` — идентификатор семейного положения;
- `gender` – пол клиента;
- `income_type` — тип занятости;
- `debt` — имел ли задолженность по возврату кредитов;
- `total_income` — ежемесячный доход;
- `purpose` — цель получения кредита;

**Навыки и инструменты**  `Python`, `pandas`, `Предобработка данных`, `.groupby()`,  `.pivot_table()`.

[В начало раздела](#Постановка-задачи) | [К содержанию проекта](#Содержание)

## Резюме проекта

**В ходе исследования проведены:**
- Предобработка данных: нахождение и заполнение пропусков, исследование и исправление артефактов в данных, преобразование типов, удаление явных и неявных дубликатов.
- Проведена оптимизация датафрейма с выделением двух новых датафреймов "словарей" и категоризация заёмщиков по уровню доходов и целям получения кредита.
- С помощью сводных таблиц проведено исследование и получены ответы на поставленные вопросы.

</br></br>
**По результатам проведенного исследования сделаны следующие выводы:**
1. С ростом количества детей в семье процент невозвратов (отношение количества клиентов имеющих просрочку к количеству не имеющих задолженности по кредиту) растет.
1. Процент просрочки по кредитам выше среди холостых и живущих в гражданском браке.
1. Процент невозвратов наибольший у группы с доходом до 30000 руб. и у группы с уровнем дохода от 50001–200000. Скорее всего это связано с тем, что в эти группы попадает наибольшее количество заёмщиков.
1. Наибольший риск просрочки по кредитам на операции с недвижимостью и автокредитам

[В начало раздела](#Резюме-проекта) | [К содержанию проекта](#Содержание)

## Краткое содержание работы

Исследование проводилось в четыре этапа:

1. [Обзор данных](#Обзор-данных) — загрузка библиотеки `pandas` и файла с исходными данными, первичное знакомство с данными посредством методов `head()` и `info()`. При загрузке файла с исходными данными применен обработчик исключений `try-except`.


2. [Предобработка данных](#Предобработка-данных) — основная и наиболее трудоёмкая часть проекта. Устранение выявленных при обзоре недостатков в данных: нарушений в стиле заголовков столбцов, заполнение пропущенных значений, удаление полных дубликатов. На этом этапе было обнаружено, что данные:
- содержали 10,1% пропусков в колонках `days_employed` и `total_income`.
- имели неявные дубликаты в колонках `education`, `family_status` и `purpose`.
- имели вещественный формат в колонке `total_income` вместо целочисленного.
- имели 71 ед. строк-дубликатов (0,33% от общего объёма данных).

</br></br>
Все столбцы датафрейма были проверены на наличие аномальных значений (артефактов). Все найденные аномальные значения устранены.

Для обработки данных использовались такие методы как `value_counts()`, `pivot_table()`, `fillna()`, `transform()`, `apply()`, `isna().sum()`, `astype()`, `str.lower()`, `duplicated().sum()` и `drop_duplicates()`.


3. [Ответы на вопросы](#Ответы-на-вопросы) — анализ данных с помощью сводных таблиц и ответы на поставленные вопросы.


4. [Формулировка общего вывода](#Общий-вывод) по результатам исследования.

</br></br>
Первоначально проект выполнялся полностью самостоятельно и был проверен ревьюером. Позднее на платформе Яндекс Практикума данный проект был преобразован в проект с полуавтоматической проверкой, состоящий из 24 заданий.

Первая часть проекта (задания 1-18) должны были выполняться в Jupyter-тренажёре. Количество заданий по предобработке данных было сокращено по сравнению с представленной версией проекта. Вторая часть проекта (задания 19-24) по сравнению с первоначальной версией содержала два дополнительных вопроса по обоснованию выбора способа обработки пропусков.

Данная версия проекта является компиляцией этих двух подходов. Разделы первоначальной (более полной) версии проекта сопоставлены с заданиями второй версии. Кроме этого, некоторые разделы содержат несколько версий выполнения задания - первоначальную, проверенную ревьюером и более позднюю, созданную после прохождения курса при подготовке проекта к публикации в портфолио.

[В начало раздела](#Краткое-содержание-работы) | [К содержанию проекта](#Содержание)

## Обзор данных
**Задача:** открыть таблицу и изучить общую информацию о данных.


### Импорт библиотек и данных
Задание 1. Импортируйте библиотеку pandas. Считайте данные из csv-файла в датафрейм и сохраните в переменную `data`.

In [1]:
# Импорт библиотеки pandas
import pandas as pd

# Импорт данных в переменную `data`
try:
    # Адрес в локальном окружении
        data = pd.read_csv('datasets/data.csv')
    
except:
    # Адрес в окружении Яндекс Практикума
    data = pd.read_csv('…/data.csv')

Задание 2. Выведите первые 20 строчек датафрейма `data` на экран.

In [2]:
# Вывод на экран первых 20 строк датафрейма
data.head(20)

children  days_employed  dob_years            education  education_id  \
0          1   -8437.673028         42               высшее             0   
1          1   -4024.803754         36              среднее             1   
2          0   -5623.422610         33              Среднее             1   
3          3   -4124.747207         32              среднее             1   
4          0  340266.072047         53              среднее             1   
5          0    -926.185831         27               высшее             0   
6          0   -2879.202052         43               высшее             0   
7          0    -152.779569         50              СРЕДНЕЕ             1   
8          2   -6929.865299         35               ВЫСШЕЕ             0   
9          0   -2188.756445         41              среднее             1   
10         2   -4171.483647         36               высшее             0   
11         0    -792.701887         40              среднее             1   
12         0            NaN         65              среднее             1   
13         0   -1846.641941         54  неоконченное высшее             2   
14         0   -1844.956182         56               высшее             0   
15         1    -972.364419         26              среднее             1   
16         0   -1719.934226         35              среднее             1   
17         0   -2369.999720         33               высшее             0   
18         0  400281.136913         53              среднее             1   
19         0  -10038.818549         48              СРЕДНЕЕ             1   

       family_status  family_status_id gender income_type  debt  \
0    женат / замужем                 0      F   сотрудник     0   
1    женат / замужем                 0      F   сотрудник     0   
2    женат / замужем                 0      M   сотрудник     0   
3    женат / замужем                 0      M   сотрудник     0   
4   гражданский брак                 1      F   пенсионер     0   
5   гражданский брак                 1      M   компаньон     0   
6    женат / замужем                 0      F   компаньон     0   
7    женат / замужем                 0      M   сотрудник     0   
8   гражданский брак                 1      F   сотрудник     0   
9    женат / замужем                 0      M   сотрудник     0   
10   женат / замужем                 0      M   компаньон     0   
11   женат / замужем                 0      F   сотрудник     0   
12  гражданский брак                 1      M   пенсионер     0   
13   женат / замужем                 0      F   сотрудник     0   
14  гражданский брак                 1      F   компаньон     1   
15   женат / замужем                 0      F   сотрудник     0   
16   женат / замужем                 0      F   сотрудник     0   
17  гражданский брак                 1      M   сотрудник     0   
18    вдовец / вдова                 2      F   пенсионер     0   
19         в разводе                 3      F   сотрудник     0   

     total_income                                 purpose  
0   253875.639453                           покупка жилья  
1   112080.014102                 приобретение автомобиля  
2   145885.952297                           покупка жилья  
3   267628.550329              дополнительное образование  
4   158616.077870                         сыграть свадьбу  
5   255763.565419                           покупка жилья  
6   240525.971920                       операции с жильем  
7   135823.934197                             образование  
8    95856.832424                   на проведение свадьбы  
9   144425.938277                 покупка жилья для семьи  
10  113943.491460                    покупка недвижимости  
11   77069.234271       покупка коммерческой недвижимости  
12            NaN                         сыграть свадьбу  
13  130458.228857                 приобретение автомобиля  
14  165127.911772              покупка жилой недвижимости  
15  116820.904450 

### Обзор датасета
Задание 3. Выведите основную информацию о датафрейме с помощью метода `info()`. 

In [3]:
# Получение общей информации о данных в датафрейме data
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21525 entries, 0 to 21524
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   children          21525 non-null  int64  
 1   days_employed     19351 non-null  float64
 2   dob_years         21525 non-null  int64  
 3   education         21525 non-null  object 
 4   education_id      21525 non-null  int64  
 5   family_status     21525 non-null  object 
 6   family_status_id  21525 non-null  int64  
 7   gender            21525 non-null  object 
 8   income_type       21525 non-null  object 
 9   debt              21525 non-null  int64  
 10  total_income      19351 non-null  float64
 11  purpose           21525 non-null  object 
dtypes: float64(2), int64(5), object(5)
memory usage: 2.0+ MB


**Результаты обзора**

Всего в исходной таблице содержится **21525** записей, разбитых на **12** столбцов:
* `children` — количество детей в семье:
    + тип переменной: количественная;
    + тип данных: целое число;
    + пропуски: отсутствуют;
    + аномальные значения: на данном этапе не обнаружены.
</br></br>
* `days_employed` — общий трудовой стаж в днях:
    + тип переменной: количественная;
    + тип данных: десятичное число;
    + пропуски: есть (общее количество записей 19351 из 21525, на данном этапе обнаружены строки с NaN);
    + аномальные значения: есть (на данном этапе обнаружены отрицательные значения переменной, а также как минимум одно подозрительное значение - `340266.072047`(932,236 лет) в строке 4).
</br></br> 
* `dob_years` — возраст клиента в годах:
    + тип переменной: количественная;
    + тип данных: целое число;
    + пропуски: отсутствуют;
    + аномальные значения: на данном этапе не обнаружены.
</br></br>
* `education` — уровень образования клиента:
    + тип переменной: категориальная, на данном этапе можно сделать вывод о наличии следующих категорий:
        - `высшее`;
        - `среднее`;
        - `неоконченное высшее`;
    + тип данных: строковый (object);
    + пропуски: отсутствуют;
    + аномальные значения: на данном этапе обнаружены строки начинающиеся со строчных букв, либо полностью набранные строчными, что приведет к дублированию названий категорий при категоризации.
</br></br> 
* `education_id` — идентификатор уровня образования:
    + тип переменной: категориальная, на данном этапе можно сделать вывод о наличии следующих категорий:
        - `education_id = 0` - высшее;
        - `education_id = 1` - среднее;
        - `education_id = 2` - неоконченное высшее;
    + тип данных: целое число;
    + пропуски: отсутствуют;
    + аномальные значения: на данном этапе не обнаружены.
</br></br>
* `family_status` — семейное положение:
    + тип переменной: категориальная, на данном этапе можно сделать вывод о наличии следующих категорий:
        - `женат / замужем`;
        - `гражданский брак`;
    + тип данных: строковый (object);
    + пропуски: отсутствуют;
    + аномальные значения: на данном этапе не обнаружены.
</br></br> 
* `family_status_id` — идентификатор семейного положения:
    + тип переменной: категориальная, на данном этапе можно сделать вывод о наличии следующих категорий:
        - `family_status_id = 0` - женат / замужем;
        - `family_status_id = 1` - гражданский брак;
    + тип данных: целое число;
    + пропуски: отсутствуют;
    + аномальные значения: на данном этапе не обнаружены.
</br></br>
* `gender` — пол клиента:
    + тип переменной: категориальная, на данном этапе можно сделать вывод о наличии следующих категорий:
        - `M`;
        - `F`;
    + тип данных: строковый (object);
    + пропуски: отсутствуют;
    + аномальные значения: на данном этапе не обнаружены.
</br></br> 
* `income_type` — тип занятости:
    + тип переменной: категориальная, на данном этапе можно сделать вывод о наличии следующих категорий:
        - `сотрудник`;
        - `пенсионер`;
        - `компаньон`;  
    + тип данных: строковый (object);
    + пропуски: отсутствуют;
    + аномальные значения: на данном этапе не обнаружены.
</br></br> 
* `debt` — имел ли задолженность по возврату кредитов:
    + тип переменной: категориальная, на данном этапе можно сделать вывод о наличии следующих категорий:
        - `debt = 0` - предположительно не имел задолженности;
        - `debt = 1` - предположительно имел задолженности;
    + тип данных: целое число;
    + пропуски: отсутствуют;
    + аномальные значения: на данном этапе не обнаружены.
</br></br>
* `total_income` — ежемесячный доход:
    + тип переменной: количественная;
    + тип данных: десятичное число;
    + пропуски: есть (общее количество записей 19351 из 21525, на данном этапе обнаружены строки с NaN);
    + аномальные значения: на данном этапе не обнаружены.
</br></br>
* `purpose` — цель получения кредита:
    + тип переменной: категориальная, на данном этапе можно сделать вывод о наличии следующих категорий:
        - `покупка жилья`;
        - `приобретение автомобиля`;
        - `сыграть свадьбу`
        - `образование`;
        - и т. д.;
    + тип данных: строковый (object);
    + пропуски: отсутствуют;
    + аномальные значения: на данном этапе не обнаружены.

</br></br>
Наименования столбцов корректные, в хорошем стиле и замены не требуют.

### Выводы по разделу 4
1. В двух столбцах `days_employed` и `total_income` есть пропущенные значения (общее количество записей 19351 из 21525, при обзоре первых 20 строк датафрейма обнаружены строки с NaN). На данном этапе можно предположить, что наличие пропусков в этих столбцах связано между собой (так как совпадает общее количество пропусков и в исследованной части таблицы пропуски в этих столбцах идут в одной строке).
2. В столбце `days_employed` встречаются как минимум два вида аномалий:
    - отрицательные значения, которых не должно быть по смыслу показателя (трудовой стаж не может быть отрицательным)
    - слишком большие значения (например, в строке 4 значение `340266.072047`, что при делении на 365 составляет 932 года)
</br></br>
3. В столбце `education` встречаются неявные дубликаты - строковые значения с капитализацией символов и без, что приведет к дублированию категорий, при категоризации

4. После заполнения пропусков в столбце `total_income` необходимо изменить тип содержащихся в нём данных на целочисленный для последующей категоризации групп клиентов по величине дохода.

5. Необходимо исследовать все столбцы, содержащие категориальные данные, на наличие явных и неявных дубликатов.

6. Необходимо сформировать дополнительные датафреймы "словарей" по уникальным значениям уровня образования `education_id` и семейного положения клиентов `family_status_id`, очистив исходный датафрейм от столбцов `education` и `family_status`.

7. Для ответа на поставленные вопросы необходимо провести категоризацию исходной таблице по уровню дохода и целям кредитования

[В начало раздела](#Обзор-данных) | [К содержанию проекта](#Содержание)

## Предобработка данных

### Заполнение пропусков

#### Нахождение пропусков

Задание 4. Выведите количество пропущенных значений для каждого столбца. Используйте комбинацию двух методов.

In [4]:
# Подсчёт пропусков
data.isna().sum()

children               0
days_employed       2174
dob_years              0
education              0
education_id           0
family_status          0
family_status_id       0
gender                 0
income_type            0
debt                   0
total_income        2174
purpose                0
dtype: int64

[В начало подраздела](#Нахождение-пропусков) | [В начало раздела](#Заполнение-пропусков) | [К содержанию проекта](#Содержание)

#### Изучение пропусков
1. Выведем на экран строки в исходной таблице, у которых есть пропуски в столбцах `days_employed` и `total_income`.
2. Подсчитаем долю строк с пропущенными значениями в этих столбцах от общего количества строк в датасете.

In [5]:
# Выводим на экран первые 5 строк выборки из датафрейма с пропусками в столбце `days_employed`
display(data[data['days_employed'].isna()].head())

# Находим долю строк с пропусками в столбце `days_employed` от общего количества строк в датасете
missed_days_employed_share = data['days_employed'].isna().sum() / len(data)

# Выводим на экран долю строк с пропусками в столбце `days_employed` от общего количества строк в датасете 
print(f'Доля строк с пропущенными значениями в столбце days_employed от общего количества строк в датасете: {missed_days_employed_share:.1%}')

# Выводим на экран первые 5 строк выборки из датафрейма с пропусками в столбце `total_income`.
display(data[data['total_income'].isna()].head())

# Находим долю строк с пропусками в столбце `total_income` от общего количества строк в датасете
missed_total_income_share = data['total_income'].isna().sum() / len(data)

# Выводим на экран долю строк с пропусками в столбце `total_income` от общего количества строк в датасете 
print(f'Доля строк с пропущенными значениями в столбце total_income от общего количества строк в датасете: {missed_total_income_share:.1%}')

children  days_employed  dob_years education  education_id  \
12         0            NaN         65   среднее             1   
26         0            NaN         41   среднее             1   
29         0            NaN         63   среднее             1   
41         0            NaN         50   среднее             1   
55         0            NaN         54   среднее             1   

            family_status  family_status_id gender  income_type  debt  \
12       гражданский брак                 1      M    пенсионер     0   
26        женат / замужем                 0      M  госслужащий     0   
29  Не женат / не замужем                 4      F    пенсионер     0   
41        женат / замужем                 0      F  госслужащий     0   
55       гражданский брак                 1      F    пенсионер     1   

    total_income                           purpose  
12           NaN                   сыграть свадьбу  
26           NaN                       образование  
29           NaN  строительство жилой недвижимости  
41           NaN  сделка с подержанным автомобилем  
55           NaN                   сыграть свадьбу

Доля строк с пропущенными значениями в столбце days_employed от общего количества строк в датасете: 10.1%


children  days_employed  dob_years education  education_id  \
12         0            NaN         65   среднее             1   
26         0            NaN         41   среднее             1   
29         0            NaN         63   среднее             1   
41         0            NaN         50   среднее             1   
55         0            NaN         54   среднее             1   

            family_status  family_status_id gender  income_type  debt  \
12       гражданский брак                 1      M    пенсионер     0   
26        женат / замужем                 0      M  госслужащий     0   
29  Не женат / не замужем                 4      F    пенсионер     0   
41        женат / замужем                 0      F  госслужащий     0   
55       гражданский брак                 1      F    пенсионер     1   

    total_income                           purpose  
12           NaN                   сыграть свадьбу  
26           NaN                       образование  
29           NaN  строительство жилой недвижимости  
41           NaN  сделка с подержанным автомобилем  
55           NaN                   сыграть свадьбу

Доля строк с пропущенными значениями в столбце total_income от общего количества строк в датасете: 10.1%


**Предварительный вывод**: датасет содержит строки с пропусками в столбцах `days_employed` и `total_income`. Сравнение выборок из датасета, содержащих строки с пропущенными значениями в этих столбцах позволяет сделать предположение, что эти пропуски допущены в одних и тех же строках. Это косвенно это подтверждается одинаковым количеством строк с пропусками по обоим столбцам (и соответственно их одинаковой долей в общем количестве строк датасета — 10,1%).

Для того, чтобы убедиться в правильности этого предположения, сначала выберем из датасета все строки у которых есть пропуски в столбце `days_employed` и нет пропусков в столбце `total_income`. Затем аналогично выберем все строки у которых есть пропуски в столбце `total_income`и нет пропусков в столбце `days_employed`. Если в обоих случаях мы получим пустые выборки, это будет означать, что пропуски в обоих столбцах содержаться в одних и тех же строках.

In [6]:
print(data.loc[(data['days_employed'].isna()) & (data['total_income'] == '')])

Empty DataFrame
Columns: [children, days_employed, dob_years, education, education_id, family_status, family_status_id, gender, income_type, debt, total_income, purpose]
Index: []


In [7]:
print(data.loc[(data['total_income'].isna()) & (data['days_employed'] == '')])

Empty DataFrame
Columns: [children, days_employed, dob_years, education, education_id, family_status, family_status_id, gender, income_type, debt, total_income, purpose]
Index: []


**Выводы:**
- Вывод по итогам обзора датасета (пп. 1. [п. 4.3](#Выводы-по-разделу)) подтверждён — обнаружены пропуски в двух столбцах: `days_employed` и `total_income`. В других столбцах пропусков в данных нет.
- Оба столбца содержат количественные переменные (количество дней трудового стажа и сумму ежемесячного дохода).
- Пропуски в столбцах `days_employed` и `total_income` находятся в одних и тех же строках.
- Доля этих строк в общем количестве строк датасета составляет 10,1%
- Наиболее вероятной причиной их возникновения является недостаточность информации при вводе данных (например, логично выглядит наличие пропусков, если величина ежемесячного дохода расчитывается от количества дней трудового стажа).
- Пропуски в столбце `days_employed` будут обработаны на следующем шаге в процессе проверки данных на аномалии и исправлении обнаруженных аномалий, а на данном этапе заполним пропуски в столбце `total_income` медианными значениями, так как 10% от всех данных достаточно большой сегмент, чтобы отказываться от него просто удалив строки с отсутствующими данными.

[В начало подраздела](#Изучение-пропусков) | [В начало раздела](#Заполнение-пропусков) | [К содержанию проекта](#Содержание)

#### Заполнение пропусков в столбце `total_income`
Задание 5. Столбец с пропущенными значениями — `total_income` — хранит данные о доходах. На сумму дохода сильнее всего влияет тип занятости, поэтому заполнить пропуски в этом столбце нужно медианным значением по каждому типу из столбца `income_type`. Для этого сделаем следующее:
1. Получим список всех уникальных значений в столбце `income_type` (заодно и проверим их на наличие аномальных и повторяющихся значений)
2. Найдем медианное значение ежемесячного дохода `total_income` для каждого типа занятости.
3. Заполним пропуски в столце `total_income` медианными значениями с учетом значений в столбце `income_type`.

##### Получение уникальных значений в столбце `income_type`

In [8]:
# Выведем на экран все уникальные значения столбца `income_type`
data['income_type'].unique()

array(['сотрудник', 'пенсионер', 'компаньон', 'госслужащий',
       'безработный', 'предприниматель', 'студент', 'в декрете'],
      dtype=object)

**Результат проверки:**
- В наборе значений столбца `income_type_unique` не обнаружены аномальные значения
- Дополнительно к выявленным ранее значениям категорий `сотрудник`, `пенсионер`, `компаньон`, в результате проверки на уникальность значений добавились `госслужащий`, `безработный`, `предприниматель`, `студент` и `в декрете`. 

##### Нахождение медианных значений в столбце `total_income` в зависимости от значения в столбце `income_type`

In [9]:
# Нахождение медианного значения ежемесячного дохода для типа занятости `сотрудник`

# Фильтруем в новый датасет строки с нужным типом занятости
employee_data = data.loc[data['income_type'] == 'сотрудник']

# Выводим на экран первые 5 строк нового датасета
display(employee_data.head())

# Выводим на экран количество строк нового датасета
print(f'Количество строк с типом занятости `сотрудник`: {len(employee_data)}')

# Находим количество пропусков в столбце `total_income` для типа данного типа занятости
missed_employee_data_total_income_sum = employee_data['total_income'].isna().sum()
print(f'Количество пропусков в столбце `total_income` для типа занятости `сотрудник`: {missed_employee_data_total_income_sum}')

# Находим медианное значение по столбцу `total_income`
employee_data_income_median = employee_data['total_income'].median()
print(f'Медианное значение ежемесячного дохода для типа занятости `сотрудник`: {employee_data_income_median}')

children  days_employed  dob_years education  education_id  \
0         1   -8437.673028         42    высшее             0   
1         1   -4024.803754         36   среднее             1   
2         0   -5623.422610         33   Среднее             1   
3         3   -4124.747207         32   среднее             1   
7         0    -152.779569         50   СРЕДНЕЕ             1   

     family_status  family_status_id gender income_type  debt   total_income  \
0  женат / замужем                 0      F   сотрудник     0  253875.639453   
1  женат / замужем                 0      F   сотрудник     0  112080.014102   
2  женат / замужем                 0      M   сотрудник     0  145885.952297   
3  женат / замужем                 0      M   сотрудник     0  267628.550329   
7  женат / замужем                 0      M   сотрудник     0  135823.934197   

                      purpose  
0               покупка жилья  
1     приобретение автомобиля  
2               покупка жилья  
3  дополнительное образование  
7                 образование

Количество строк с типом занятости `сотрудник`: 11119
Количество пропусков в столбце `total_income` для типа занятости `сотрудник`: 1105
Медианное значение ежемесячного дохода для типа занятости `сотрудник`: 142594.39684740017


In [10]:
# Нахождение медианного значения ежемесячного дохода для типа занятости `пенсионер`

# Фильтруем в новый датасет строки с нужным типом занятости
pensioner_data = data.loc[data['income_type'] == 'пенсионер']

# Выводим на экран первые 5 строк нового датасета
display(pensioner_data.head())

# Выводим на экран количество строк нового датасета
print(f'Количество строк с типом занятости `пенсионер`: {len(pensioner_data)}')

# Находим количество пропусков в столбце `total_income` для типа данного типа занятости
missed_pensioner_data_total_income_sum = pensioner_data['total_income'].isna().sum()
print(f'Количество пропусков в столбце `total_income` для типа занятости `пенсионер`: {missed_pensioner_data_total_income_sum}')

# Находим медианное значение по столбцу `total_income`
pensioner_data_income_median = pensioner_data['total_income'].median()
print(f'Медианное значение ежемесячного дохода для типа занятости `пенсионер`: {pensioner_data_income_median}')

children  days_employed  dob_years education  education_id  \
4          0  340266.072047         53   среднее             1   
12         0            NaN         65   среднее             1   
18         0  400281.136913         53   среднее             1   
24         1  338551.952911         57   среднее             1   
25         0  363548.489348         67   среднее             1   

            family_status  family_status_id gender income_type  debt  \
4        гражданский брак                 1      F   пенсионер     0   
12       гражданский брак                 1      M   пенсионер     0   
18         вдовец / вдова                 2      F   пенсионер     0   
24  Не женат / не замужем                 4      F   пенсионер     0   
25        женат / замужем                 0      M   пенсионер     0   

     total_income                                purpose  
4   158616.077870                        сыграть свадьбу  
12            NaN                        сыграть свадьбу  
18   56823.777243     на покупку подержанного автомобиля  
24  290547.235997  операции с коммерческой недвижимостью  
25   55112.757732                   покупка недвижимости

Количество строк с типом занятости `пенсионер`: 3856
Количество пропусков в столбце `total_income` для типа занятости `пенсионер`: 413
Медианное значение ежемесячного дохода для типа занятости `пенсионер`: 118514.48641164352


In [11]:
# Нахождение медианного значения ежемесячного дохода для типа занятости `компаньон`

# Фильтруем в новый датасет строки с нужным типом занятости
companion_data = data.loc[data['income_type'] == 'компаньон']

# Выводим на экран первые 5 строк нового датасета
display(companion_data.head())

# Выводим на экран количество строк нового датасета
print(f'Количество строк с типом занятости `компаньон`: {len(companion_data)}')

# Находим количество пропусков в столбце `total_income` для типа данного типа занятости
missed_companion_data_total_income_sum = companion_data['total_income'].isna().sum()
print(f'Количество пропусков в столбце `total_income` для типа занятости `компаньон`: {missed_companion_data_total_income_sum}')

# Находим медианное значение по столбцу `total_income`
companion_data_income_median = companion_data['total_income'].median()
print(f'Медианное значение ежемесячного дохода для типа занятости `компаньон`: {companion_data_income_median}')

children  days_employed  dob_years education  education_id  \
5          0    -926.185831         27    высшее             0   
6          0   -2879.202052         43    высшее             0   
10         2   -4171.483647         36    высшее             0   
14         0   -1844.956182         56    высшее             0   
33         0   -1548.637544         48   среднее             1   

       family_status  family_status_id gender income_type  debt  \
5   гражданский брак                 1      M   компаньон     0   
6    женат / замужем                 0      F   компаньон     0   
10   женат / замужем                 0      M   компаньон     0   
14  гражданский брак                 1      F   компаньон     1   
33   женат / замужем                 0      F   компаньон     0   

     total_income                     purpose  
5   255763.565419               покупка жилья  
6   240525.971920           операции с жильем  
10  113943.491460        покупка недвижимости  
14  165127.911772  покупка жилой недвижимости  
33  157245.786233               покупка жилья

Количество строк с типом занятости `компаньон`: 5085
Количество пропусков в столбце `total_income` для типа занятости `компаньон`: 508
Медианное значение ежемесячного дохода для типа занятости `компаньон`: 172357.95096577113


In [12]:
# Нахождение медианного значения ежемесячного дохода для типа занятости `госслужащий`

# Фильтруем в новый датасет строки с нужным типом занятости
civil_servant_data = data.loc[data['income_type'] == 'госслужащий']

# Выводим на экран первые 5 строк нового датасета
display(civil_servant_data.head())

# Выводим на экран количество строк нового датасета
print(f'Количество строк с типом занятости `госслужащий`: {len(civil_servant_data)}')

# Находим количество пропусков в столбце `total_income` для типа данного типа занятости
missed_civil_servant_data_total_income_sum = civil_servant_data['total_income'].isna().sum()
print(f'Количество пропусков в столбце `total_income` для типа занятости `госслужащий`: {missed_civil_servant_data_total_income_sum}')

# Находим медианное значение по столбцу `total_income`
civil_servant_data_income_median = civil_servant_data['total_income'].median()
print(f'Медианное значение ежемесячного дохода для типа занятости `госслужащий`: {civil_servant_data_income_median}')

children  days_employed  dob_years education  education_id  \
26         0            NaN         41   среднее             1   
41         0            NaN         50   среднее             1   
47         1   -2689.137274         33    высшее             0   
62         0   -7845.649233         48    Высшее             0   
70         1   -2802.226671         28    ВЫСШЕЕ             0   

            family_status  family_status_id gender  income_type  debt  \
26        женат / замужем                 0      M  госслужащий     0   
41        женат / замужем                 0      F  госслужащий     0   
47       гражданский брак                 1      M  госслужащий     0   
62  Не женат / не замужем                 4      M  госслужащий     0   
70        женат / замужем                 0      M  госслужащий     0   

     total_income                            purpose  
26            NaN                        образование  
41            NaN   сделка с подержанным автомобилем  
47  356277.909345              на проведение свадьбы  
62  435388.195272      получение высшего образования  
70  207561.466998  покупка коммерческой недвижимости

Количество строк с типом занятости `госслужащий`: 1459
Количество пропусков в столбце `total_income` для типа занятости `госслужащий`: 147
Медианное значение ежемесячного дохода для типа занятости `госслужащий`: 150447.9352830068


In [13]:
# Нахождение медианного значения ежемесячного дохода для типа занятости `безработный`

# Фильтруем в новый датасет строки с нужным типом занятости
unemployed_data = data.loc[data['income_type'] == 'безработный']

# Выводим на экран первые 5 строк нового датасета
display(unemployed_data.head())

# Выводим на экран количество строк нового датасета
print(f'Количество строк с типом занятости `безработный`: {len(unemployed_data)}')

# Находим количество пропусков в столбце `total_income` для типа данного типа занятости
missed_unemployed_data_total_income_sum = unemployed_data['total_income'].isna().sum()
print(f'Количество пропусков в столбце `total_income` для типа занятости `безработный`: {missed_unemployed_data_total_income_sum}')

# Находим медианное значение по столбцу `total_income`
unemployed_data_income_median = unemployed_data['total_income'].median()
print(f'Медианное значение ежемесячного дохода для типа занятости `безработный`: {unemployed_data_income_median}')

children  days_employed  dob_years education  education_id  \
3133          1  337524.466835         31   среднее             1   
14798         0  395302.838654         45    Высшее             0   

          family_status  family_status_id gender  income_type  debt  \
3133    женат / замужем                 0      M  безработный     1   
14798  гражданский брак                 1      F  безработный     0   

        total_income                  purpose  
3133    59956.991984  покупка жилья для сдачи  
14798  202722.511368             ремонт жилью

Количество строк с типом занятости `безработный`: 2
Количество пропусков в столбце `total_income` для типа занятости `безработный`: 0
Медианное значение ежемесячного дохода для типа занятости `безработный`: 131339.7516762103


**Обращает на себя внимание**, что по типу занятости `безработный` в датасете всего две строки в которых нет пропуска. Однако, во второй строке присутствует явно аномальное значение ежемесячного дохода — `202722.511368`, что превышает медианный доход таких групп, как, например, `сотрудник` или `госслужащий`. Возможно здесь допущена ошибка при вводе — неправильно поставлена запятая при вводе и надо скорректировать значение на `20272.2511368`.

In [14]:
# Нахождение медианного значения ежемесячного дохода для типа занятости `предприниматель`

# Фильтруем в новый датасет строки с нужным типом занятости
entrepreneur_data = data.loc[data['income_type'] == 'предприниматель']

# Выводим на экран первые 5 строк нового датасета
display(entrepreneur_data.head())

# Выводим на экран количество строк нового датасета
print(f'Количество строк с типом занятости `предприниматель`: {len(entrepreneur_data)}')

# Находим количество пропусков в столбце `total_income` для типа данного типа занятости
missed_entrepreneur_data_total_income_sum = entrepreneur_data['total_income'].isna().sum()
print(f'Количество пропусков в столбце `total_income` для типа занятости `предприниматель`: {missed_entrepreneur_data_total_income_sum}')

# Находим медианное значение по столбцу `total_income`
entrepreneur_data_income_median = entrepreneur_data['total_income'].median()
print(f'Медианное значение ежемесячного дохода для типа занятости `предприниматель`: {entrepreneur_data_income_median}')

children  days_employed  dob_years education  education_id  \
5936          0            NaN         58    высшее             0   
18697         0    -520.848083         27    высшее             0   

          family_status  family_status_id gender      income_type  debt  \
5936    женат / замужем                 0      M  предприниматель     0   
18697  гражданский брак                 1      F  предприниматель     0   

        total_income                     purpose  
5936             NaN  покупка жилой недвижимости  
18697  499163.144947       на проведение свадьбы

Количество строк с типом занятости `предприниматель`: 2
Количество пропусков в столбце `total_income` для типа занятости `предприниматель`: 1
Медианное значение ежемесячного дохода для типа занятости `предприниматель`: 499163.1449470857


**Обращает на себя внимание**, что по типу занятости `предприниматель` в датасете всего две строки и одна из них с пропуском значения. Таким образом, медианный доход по этой группе может быть сильно искажен. Возможно, в данном случае следует брать не медианное, а среднее значение для заполнения пропуска.

In [15]:
# Находим среднее значение по столбцу `total_income` для типа занятости `предприниматель`
entrepreneur_data_income_avg = entrepreneur_data['total_income'].median() / 2
print(f'Среднее значение ежемесячного дохода для типа занятости `предприниматель`: {entrepreneur_data_income_avg}')

Среднее значение ежемесячного дохода для типа занятости `предприниматель`: 249581.57247354285


In [16]:
# Нахождение медианного значения ежемесячного дохода для типа занятости `студент`

# Фильтруем в новый датасет строки с нужным типом занятости
student_data = data.loc[data['income_type'] == 'студент']

# Выводим на экран первые 5 строк нового датасета
display(student_data.head())

# Выводим на экран количество строк нового датасета
print(f'Количество строк с типом занятости `студент`: {len(student_data)}')

# Находим количество пропусков в столбце `total_income` для типа данного типа занятости
missed_student_data_total_income_sum = student_data['total_income'].isna().sum()
print(f'Количество пропусков в столбце `total_income` для типа занятости `студент`: {missed_student_data_total_income_sum}')

# Находим медианное значение по столбцу `total_income`
student_data_income_median = student_data['total_income'].median()
print(f'Медианное значение ежемесячного дохода для типа занятости `студент`: {student_data_income_median}')

children  days_employed  dob_years education  education_id  \
9410         0    -578.751554         22    высшее             0   

              family_status  family_status_id gender income_type  debt  \
9410  Не женат / не замужем                 4      M     студент     0   

      total_income                                 purpose  
9410  98201.625314  строительство собственной недвижимости

Количество строк с типом занятости `студент`: 1
Количество пропусков в столбце `total_income` для типа занятости `студент`: 0
Медианное значение ежемесячного дохода для типа занятости `студент`: 98201.62531401133


In [17]:
# Нахождение медианного значения ежемесячного дохода для типа занятости `в декрете`

# Фильтруем в новый датасет строки с нужным типом занятости
maternity_leave_data = data.loc[data['income_type'] == 'в декрете']

# Выводим на экран первые 5 строк нового датасета
display(maternity_leave_data.head())

# Выводим на экран количество строк нового датасета
print(f'Количество строк с типом занятости `в декрете`: {len(maternity_leave_data)}')

# Находим количество пропусков в столбце `total_income` для типа данного типа занятости
missed_maternity_leave_data_total_income_sum = maternity_leave_data['total_income'].isna().sum()
print(f'Количество пропусков в столбце `total_income` для типа занятости `в декрете`: {missed_maternity_leave_data_total_income_sum}')

# Находим медианное значение по столбцу `total_income`
maternity_leave_data_income_median = maternity_leave_data['total_income'].median()
print(f'Медианное значение ежемесячного дохода для типа занятости `в декрете`: {maternity_leave_data_income_median}')

children  days_employed  dob_years education  education_id  \
20845         2   -3296.759962         39   СРЕДНЕЕ             1   

         family_status  family_status_id gender income_type  debt  \
20845  женат / замужем                 0      F   в декрете     1   

       total_income     purpose  
20845  53829.130729  автомобиль

Количество строк с типом занятости `в декрете`: 1
Количество пропусков в столбце `total_income` для типа занятости `в декрете`: 0
Медианное значение ежемесячного дохода для типа занятости `в декрете`: 53829.13072905995


**Выводы**

Для наглядности сведем результаты расчетов медианных значений ежемесячного дохода в зависимости от типа занятости в одну таблицу:

In [18]:
def total_income_info(data):
    total_income_info = pd.DataFrame({'income_type': data['income_type'].unique(), 
    'всего строк': [len(employee_data), len(pensioner_data), len(companion_data), len(civil_servant_data),
                    len(unemployed_data), len(entrepreneur_data), len(student_data), len(maternity_leave_data)],
    'пропусков' : [missed_employee_data_total_income_sum,
                   missed_pensioner_data_total_income_sum,
                   missed_companion_data_total_income_sum,
                   missed_civil_servant_data_total_income_sum,
                   missed_unemployed_data_total_income_sum,
                   missed_entrepreneur_data_total_income_sum,
                   missed_student_data_total_income_sum,
                   missed_maternity_leave_data_total_income_sum],
    'доля пропусков' : [missed_employee_data_total_income_sum / len(employee_data),
                       missed_pensioner_data_total_income_sum / len(pensioner_data),
                       missed_companion_data_total_income_sum / len(companion_data),
                       missed_civil_servant_data_total_income_sum / len(civil_servant_data),
                       missed_unemployed_data_total_income_sum / len(unemployed_data),
                       missed_entrepreneur_data_total_income_sum / len(entrepreneur_data),
                       missed_student_data_total_income_sum / len(student_data),
                       missed_maternity_leave_data_total_income_sum / len(maternity_leave_data)],
    'медиана ежмес. дохода' : [employee_data_income_median,
                           pensioner_data_income_median,
                           companion_data_income_median,
                           civil_servant_data_income_median,
                           unemployed_data_income_median,
                           entrepreneur_data_income_median,
                           student_data_income_median,
                           maternity_leave_data_income_median]})
    display(total_income_info)

In [19]:
total_income_info (data)

income_type  всего строк  пропусков  доля пропусков  \
0        сотрудник        11119       1105        0.099379   
1        пенсионер         3856        413        0.107106   
2        компаньон         5085        508        0.099902   
3      госслужащий         1459        147        0.100754   
4      безработный            2          0        0.000000   
5  предприниматель            2          1        0.500000   
6          студент            1          0        0.000000   
7        в декрете            1          0        0.000000   

   медиана ежмес. дохода  
0          142594.396847  
1          118514.486412  
2          172357.950966  
3          150447.935283  
4          131339.751676  
5          499163.144947  
6           98201.625314  
7           53829.130729

**По результатам анализа можно сделать следующие выводы:**
- в строках со значениями типа занятости `сотрудник`, `пенсионер`, `компаньон`, `госслужащий` пропуски в столбце `total_income` составляют около 10% от объёма данных, что соответствует показателю по всем датасету и могут быть заменены медианными значениями показателя для каждой из категорий
- в строках со значениями типа занятости `безработный` пропусков нет, но из-за подозрительного значения в одной из строк медианный ежемесячный доход по этой категории выглядит аномально большим. На данном этапе ничего менять не будем, но требуется дополнительное исследование данной ситуации. Возможная причина — ошибка при вводе данных.
- в одной из двух строк с категорией `предприниматель` пропуск не позволяет корректно рассчитать медианное значение. Вместо пропуска в данном случае необходимо подставить среднее значение по двум строкам.
- в строках со значениями типа занятости `студент` и `в декрете` пропусков нет, ничего менять не надо.

[В начало подраздела](#Заполнение-пропусков-в-столбце-total_income) | [В начало раздела](#Заполнение-пропусков) | [К содержанию проекта](#Содержание)

##### Заполнение пропусков. Вариант 1 (первоначальный)

In [20]:
# Заполнение пропусков в категории 'сотрудник' медианными значениями

#rows = (data['total_income'].isna()) & (data['income_type'] == 'сотрудник')
#data.loc[rows, "total_income"] = employee_data_income_median
#missed_employee_data_total_income_sum = data.loc[rows, "total_income"].isna().sum()
#print(f'Количество пропусков в столбце `total_income` для типа занятости `пенсионер`: {missed_employee_data_total_income_sum}')

# Заполнение пропусков в категории 'пенсионер' медианными значениями

#rows = (data['total_income'].isna()) & (data['income_type'] == 'пенсионер')
#data.loc[rows, "total_income"] = pensioner_data_income_median
#missed_pensioner_data_total_income_sum = data.loc[rows, "total_income"].isna().sum()
#print(f'Количество пропусков в столбце `total_income` для типа занятости `пенсионер`: {missed_pensioner_data_total_income_sum}')

# Заполнение пропусков в категории 'компаньон' медианными значениями

#rows = (data['total_income'].isna()) & (data['income_type'] == 'компаньон')
#data.loc[rows, "total_income"] = companion_data_income_median
#missed_companion_data_total_income_sum = data.loc[rows, "total_income"].isna().sum()
#print(f'Количество пропусков в столбце `total_income` для типа занятости `компаньон`: {missed_companion_data_total_income_sum}')

# Заполнение пропусков в категории 'госслужащий' медианными значениями

#rows = (data['total_income'].isna()) & (data['income_type'] == 'госслужащий')
#data.loc[rows, "total_income"] = civil_servant_data_income_median
#missed_civil_servant_data_total_income_sum = data.loc[rows, "total_income"].isna().sum()
#print(f'Количество пропусков в столбце `total_income` для типа занятости `госслужащий`: {missed_civil_servant_data_total_income_sum}')

# Заполнение пропусков в категории 'предприниматель' средним значением и расчет новой медианы

#rows = (data['total_income'].isna()) & (data['income_type'] == 'предприниматель')

#Заполняем пропуск средним значением ежемесячного дохода для категории предприниматель
#data.loc[rows, "total_income"] = entrepreneur_data_income_avg
#missed_entrepreneur_data_total_income_sum = data.loc[rows, "total_income"].isna().sum()
#print(f'Количество пропусков в столбце `total_income` для типа занятости `предприниматель`: {missed_entrepreneur_data_total_income_sum}')

#Пересчитываем медианное значение с учетом заполненного пропуска
#entrepreneur_data_income_median = data.loc[data['income_type'] == 'предприниматель']['total_income'].median()

##### Заполнение пропусков. Вариант 2 (после ревью)

In [21]:
#for i in data['income_type'].unique():
#    data.loc[(data['income_type'] == i) & (data['total_income'].isna()), 'total_income'] = data.loc[(data['income_type'] == i), 'total_income'].median()
    
# Заполнение пропусков в категории 'предприниматель' средним значением и расчет новой медианы

#rows = (data['total_income'].isna()) & (data['income_type'] == 'предприниматель')

#Заполняем пропуск средним значением ежемесячного дохода для категории предприниматель
#data.loc[rows, "total_income"] = entrepreneur_data_income_avg
#missed_entrepreneur_data_total_income_sum = data.loc[rows, "total_income"].isna().sum()
#print(f'Количество пропусков в столбце `total_income` для типа занятости `предприниматель`: {missed_entrepreneur_data_total_income_sum}')

#Пересчитываем медианное значение с учетом заполненного пропуска
#entrepreneur_data_income_median = data.loc[data['income_type'] == 'предприниматель']['total_income'].median()

##### Заполнение пропусков. Вариант 3 (после прохождения курса)

In [22]:
data['total_income'] = data['total_income'].fillna(data.groupby('income_type')['total_income'].transform('median'))

##### Проверка заполнения пропусков

In [23]:
# Расчет общей суммы ежемесячного дохода для вычислений долей в функции `total_income_info (data)`
missed_employee_data_total_income_sum = data.loc[(data['total_income'].isna()) & (data['income_type'] == 'сотрудник'), "total_income"].isna().sum()
missed_pensioner_data_total_income_sum = data.loc[(data['total_income'].isna()) & (data['income_type'] == 'пенсионер'), "total_income"].isna().sum()
missed_companion_data_total_income_sum = data.loc[(data['total_income'].isna()) & (data['income_type'] == 'компаньон'), "total_income"].isna().sum()
missed_civil_servant_data_total_income_sum = data.loc[(data['total_income'].isna()) & (data['income_type'] == 'госслужащий'), "total_income"].isna().sum()
missed_entrepreneur_data_total_income_sum = data.loc[(data['total_income'].isna()) & (data['income_type'] == 'предприниматель'), "total_income"].isna().sum()

# Проверка заполнения пропусков
total_income_info (data)

income_type  всего строк  пропусков  доля пропусков  \
0        сотрудник        11119          0             0.0   
1        пенсионер         3856          0             0.0   
2        компаньон         5085          0             0.0   
3      госслужащий         1459          0             0.0   
4      безработный            2          0             0.0   
5  предприниматель            2          0             0.0   
6          студент            1          0             0.0   
7        в декрете            1          0             0.0   

   медиана ежмес. дохода  
0          142594.396847  
1          118514.486412  
2          172357.950966  
3          150447.935283  
4          131339.751676  
5          499163.144947  
6           98201.625314  
7           53829.130729

[В начало подраздела](#Заполнение-пропусков-в-столбце-total_income) | [В начало раздела](#Заполнение-пропусков) | [К содержанию проекта](#Содержание)

#### Вывод по подразделу 5.1

✅ Пропуски в столбце `total_income` заполнены медианными значениями по каждому типу из столбца `income_type`.

[В начало раздела](#Заполнение-пропусков) | [К содержанию проекта](#Содержание)

### Проверка данных на аномалии и исправления

Проверка данных на аномалии при выполнении проекта была проведена в порядке следования столбцов в исходной таблице. Позднее эта часть проекта была преобразована из самостоятельного исследования в набор задач для прохождения на тренажере платформы Яндекс Практикума. Вследствие этого, номера заданий, взятых из более поздней (тренажерной) версии проекта на платформе следуют не по порядку.

#### Проверка столбца `children`

##### Поиск аномальных значений в столбце `children`

Задание 8. Выведите перечень уникальных значений столбца `children`.

In [24]:
# Выведем на экран все уникальные значения столбца `children`
data['children'].unique()

array([ 1,  0,  3,  2, -1,  4, 20,  5], dtype=int64)

**Результат проверки:** в наборе значений столбца 'children' обнаружено аномальное значение `-1` и подозрительное значение `20`. Можно предположить, что в обоих случаях имеет место ошибка при вводе (в первом случае ошибочно ввели минус, а во втором, 20 вместо 2). Для того, чтобы принять решение как поступить с данными значениями, сделаем обзор и оценим количество строк, содержащих данные аномалии.

##### Анализ аномальных значений в столбце `children`

In [25]:
# Фильтруем в новый датасет строки с нужным аномальным значением
children_negative_data = data[data['children'] == -1]

# Выводим на экран новый датасет полностью, чтобы оценить есть ли взаимосвязь аномальных значений с какими-то другими в датасете
display(children_negative_data)
print(f'Всего строк с со значением `-1` в столбце `children`: {children_negative_data.shape[0]}')
print(f'Доля строк с со значением `-1` в столбце `children` в датасете: {(children_negative_data.shape[0] / data.shape[0]):.2%}')

children  days_employed  dob_years            education  education_id  \
291          -1   -4417.703588         46              среднее             1   
705          -1    -902.084528         50              среднее             1   
742          -1   -3174.456205         57              среднее             1   
800          -1  349987.852217         54              среднее             1   
941          -1            NaN         57              Среднее             1   
1363         -1   -1195.264956         55              СРЕДНЕЕ             1   
1929         -1   -1461.303336         38              среднее             1   
2073         -1   -2539.761232         42              среднее             1   
3814         -1   -3045.290443         26              Среднее             1   
4201         -1    -901.101738         41              среднее             1   
4402         -1  398001.302888         64              СРЕДНЕЕ             1   
4542         -1   -1811.899756         32              среднее             1   
5272         -1   -1143.485347         46              среднее             1   
6013         -1   -1361.258696         46               высшее             0   
6385         -1  370215.476226         48              среднее             1   
7190         -1   -5928.202068         34              СРЕДНЕЕ             1   
7278         -1    -526.318451         51              среднее             1   
7615         -1            NaN         35              среднее             1   
7685         -1   -3237.360455         53              среднее             1   
8229         -1   -1803.441074         54               высшее             0   
8251         -1   -3113.998449         31              среднее             1   
8561         -1    -195.479496         31              среднее             1   
9565         -1   -2896.629686         34               высшее             0   
9574         -1   -2710.419901         28               высшее             0   
10177        -1   -1743.604011         37              среднее             1   
10365        -1  345774.125957         63               ВЫСШЕЕ             0   
10918        -1  340499.039342         50              среднее             1   
11109        -1   -3438.463024         59              среднее             1   
11268        -1   -1048.782203         30               высшее             0   
11617        -1    -370.827130         27              среднее             1   
12304        -1   -8493.101252         61  неоконченное высшее             2   
13786        -1            NaN         42              среднее             1   
14357        -1    -268.337037         23              среднее             1   
15147        -1   -9851.184337         44              среднее             1   
15435        -1   -3614.220232         40               высшее             0   
16129        -1    -457.861760         33              среднее             1   
16265        -1   -2802.218127         40               высшее             0   
17095        -1   -2809.693200         34              среднее             1   
17429        -1    -895.379738         37              среднее             1   
17657        -1   -4571.957475         41              среднее             1   
18219        -1   -3575.215641         33              среднее             1   
19100        -1    -617.246968         38              среднее             1   
19366        -1    -372.034749         43              СРЕДНЕЕ             1   
19417        -1  350340.760224         28              среднее             1   
20393        -1  355157.107212         69              среднее             1   
20717        -1    -661.822321         32               высшее             0   
21140        -1   -1422.668059         44              среднее             1   

               family_status  family_status_id gender  income_type  debt  \
291         гражданский брак                 1      F    сотрудник     0   
705          ж

Всего строк с со значением `-1` в столбце `children`: 47
Доля строк с со значением `-1` в столбце `children` в датасете: 0.22%


In [26]:
# Фильтруем в новый датасет строки с нужным аномальным значением
children_excess_data = data[data['children'] == 20]

# Выводим на экран новый датасет полностью, чтобы оценить есть ли взаимосвязь аномальных значений с какими-то другими в датасете
display(children_excess_data)
print(f'Всего строк с со значением `20` в столбце `children`: {children_excess_data.shape[0]}')
print(f'Доля строк с со значением `20` в столбце `children` в датасете: {(children_excess_data.shape[0] / data.shape[0]):.2%}')

children  days_employed  dob_years education  education_id  \
606          20    -880.221113         21   среднее             1   
720          20    -855.595512         44   среднее             1   
1074         20   -3310.411598         56   среднее             1   
2510         20   -2714.161249         59    высшее             0   
2941         20   -2161.591519          0   среднее             1   
...         ...            ...        ...       ...           ...   
21008        20   -1240.257910         40   среднее             1   
21325        20    -601.174883         37   среднее             1   
21390        20            NaN         53   среднее             1   
21404        20    -494.788448         52   среднее             1   
21491        20    -173.954460         27   среднее             1   

         family_status  family_status_id gender income_type  debt  \
606    женат / замужем                 0      M   компаньон     0   
720    женат / замужем                 0      F   компаньон     0   
1074   женат / замужем                 0      F   сотрудник     1   
2510    вдовец / вдова                 2      F   сотрудник     0   
2941   женат / замужем                 0      F   сотрудник     0   
...                ...               ...    ...         ...   ...   
21008  женат / замужем                 0      F   сотрудник     1   
21325  женат / замужем                 0      F   компаньон     0   
21390  женат / замужем                 0      M   компаньон     0   
21404  женат / замужем                 0      M   компаньон     0   
21491  женат / замужем                 0      F   сотрудник     0   

        total_income                                purpose  
606    145334.865002                          покупка жилья  
720    112998.738649                   покупка недвижимости  
1074   229518.537004                  получение образования  
2510   264474.835577  операции с коммерческой недвижимостью  
2941   199739.941398                  на покупку автомобиля  
...              ...                                    ...  
21008  133524.010303                        свой автомобиль  
21325  102986.065978                 профильное образование  
21390  172357.950966             покупка жилой недвижимости  
21404  156629.683642        операции со своей недвижимостью  
21491  155520.899688     на покупку подержанного автомобиля  

[76 rows x 12 columns]

Всего строк с со значением `20` в столбце `children`: 76
Доля строк с со значением `20` в столбце `children` в датасете: 0.35%


**Выводы по результатам анализа аномальных значений в столбце `children`**:

* Взаимосвязи между аномальными значениями в столбце `children` и другими данными не выявлено. Таким образом, можно принять гипотезу об ошибочном вводе данных.
* Доля строк с ошибочными значениями в столбце `children` относительно общего объёма датасета мала. Таким образом, ни удаление этих строк из датасета, ни изменение их значений на условно правильные скорее всего не приведет к существенным искажениям данных на последующих шагах анализа.
* Однако, учитывая, что одним из вопросов исследования является наличие зависимости между количеством детей и возвратом кредита в срок, не будем удалять строки с аномальными значениями из датасета, а исправление проведем путём замены значений `-1` в соответствующих строках на `1` и значения `20` на `2`.

##### Исправление аномальных значений  в столбце `children`

**Первоначальная версия проекта:** исправление аномальных значений в столбце `children`

In [27]:
# Вариант 1 (первоначальный)

# Выбираем строки со значением `-1` в столбце 'children'.
# rows = data['children'] == -1
# Заменяем значение '-1' на его значение по модулю
# data.loc[rows, 'children'] = rows.abs()


# Выбираем строки со значением `20` в столбце 'children'.
# rows = data['children'] == 20
# Заменяем значение '20' на `2`
# data.loc[rows, 'children'] = 2

# Вариант 2 (после прохождения курса)

# Замена значений -1 на 1 и 20 на 2 в столбце "children"
# data['children'] = data['children'].replace({-1: 1, 20: 2})

**Поздняя версия проекта:** удаление строк с аномальными значениями в столбце `children`

Задание 9. В столбце `children` есть два аномальных значения. Удалите строки, в которых встречаются такие аномальные значения из датафрейма `data`.

In [28]:
# Удаление строк с аномальными значениями -1 и 20 в столбце "children"
data = data[(data['children'] != -1) & (data['children'] != 20)]

##### Проверка исправления аномальных значений  в столбце `children`

Задание 10. Ещё раз выведите перечень уникальных значений столбца `children`, чтобы убедиться, что артефакты удалены.

In [29]:
data['children'].unique()

array([1, 0, 3, 2, 4, 5], dtype=int64)

##### Вывод по подразделу 5.2.1

✅ Артефакты в столбце `children` устранены.

[В начало подраздела](#Проверка-столбца-children) | [В начало раздела](#Проверка-данных-на-аномалии-и-исправления) | [К содержанию проекта](#Содержание)

#### Проверка столбца `days_employed`

В наборе значений столбца `days_employed` обнаружены пропуски (пп. 1. [п. 4.3](#Выводы-по-разделу)) и аномальные значения. Для того, чтобы попытаться определить возможные причины появления таких данных, создадим функцию `days_employed_info (data)`, которая будет собирать в датафрейм количество отрицательных, нулевых и положительных значений, минимальные, средние, медианные и максимальные значения из столбца `days_employed` для каждой категории `income_type` и выводить табличку с ними на экран.

##### Поиск аномальных значений в столбце `days_employed`

In [30]:
# Функция days_employed_info (data) будет собирать в датафрейм количество отрицательных, нулевых и положительных значений,
# минимальные, средние, медианные и максимальные значения из столбца 'days_employed' для каждой категории 'income_type',
# а также количество пропусков и выводить табличку с ними на экран

def days_employed_info(data):

    income_type_1 = [] # Столбец с категорией 'income_type'
    income_type_2 = [] # Столбец c количеством отрицательных значений в 'days_employed' для каждого 'income_type'
    income_type_3 = [] # Столбец c количеством нулевых значений в 'days_employed' для каждого 'income_type'
    income_type_4 = [] # Столбец c количеством положительных значений в 'days_employed' для каждого 'income_type'
    income_type_5 = [] # Столбец c минимальными значениями в 'days_employed' для каждого 'income_type'
    income_type_6 = [] # Столбец cо средними значениями в 'days_employed' для каждого 'income_type'
    income_type_7 = [] # Столбец c медианными значениями в 'days_employed' для каждого 'income_type'
    income_type_8 = [] # Столбец c максимальными значениями в 'days_employed' для каждого 'income_type'
    income_type_9 = [] # Столбец c пропусками в 'days_employed' для каждого 'income_type'    

# В цикле по уникальным значениям 'income_type' заполняем списки для каждого из столбцов    
    
    for income_type in data['income_type'].unique():
        income_type_1.append(income_type)
        income_type_2.append(data[(data['days_employed'] < 0) & (data['income_type'] == income_type)].shape[0])
        income_type_3.append(data[(data['days_employed'] == 0) & (data['income_type'] == income_type)].shape[0])
        income_type_4.append(data[(data['days_employed'] > 0) & (data['income_type'] == income_type)].shape[0])
        income_type_5.append(data[data['income_type'] == income_type]['days_employed'].min())
        income_type_6.append(data[data['income_type'] == income_type]['days_employed'].mean())
        income_type_7.append(data[data['income_type'] == income_type]['days_employed'].median())
        income_type_8.append(data[data['income_type'] == income_type]['days_employed'].max())
        income_type_9.append(data[data['income_type'] == income_type]['days_employed'].isna().sum())
        
# Создаем датафрейм, содержащий результаты обзора данных         
        
    days_employed_info = pd.DataFrame({'income_type': income_type_1,
                                       'negative': income_type_2,
                                       'zero': income_type_3,
                                       'positive': income_type_4,
                                       'min': income_type_5,
                                       'mean': income_type_6,
                                       'median': income_type_7,
                                       'max': income_type_8,
                                       'NaN': income_type_9,
                                       })
# Выводим датафрем на экран 

    display(days_employed_info)

In [31]:
# Вызов функции для описания столбца 'days_employed'
days_employed_info (data)

# Определим количество строк, содержащих отрицательные значения в столбце 'days_employed'
print('Количество строк с отрицательными `days_employed`, шт.:', data[data['days_employed'] < 0].shape[0])
print('Доля строк с отрицательными `days_employed` в датасете, %:', (data[data['days_employed'] < 0].shape[0]/len(data)*100))
print('Количество строк с пропусками в `days_employed`, шт.:', data['days_employed'].isna().sum())

income_type  negative  zero  positive            min           mean  \
0        сотрудник      9949     0         0  -18388.949901   -2323.653522   
1        пенсионер         0     0      3429  328728.720605  365025.091981   
2        компаньон      4550     0         0  -17615.563266   -2118.257358   
3      госслужащий      1307     0         0  -15193.032201   -3403.534603   
4      безработный         0     0         2  337524.466835  366413.652744   
5  предприниматель         1     0         0    -520.848083    -520.848083   
6          студент         1     0         0    -578.751554    -578.751554   
7        в декрете         1     0         0   -3296.759962   -3296.759962   

          median            max   NaN  
0   -1572.328285     -24.141633  1101  
1  365286.622650  401755.400475   410  
2   -1555.947387     -30.195337   504  
3   -2689.137274     -39.954170   146  
4  366413.652744  395302.838654     0  
5    -520.848083    -520.848083     1  
6    -578.751554    -578.751554     0  
7   -3296.759962   -3296.759962     0

Количество строк с отрицательными `days_employed`, шт.: 15809
Доля строк с отрицательными `days_employed` в датасете, %: 73.86692832445566
Количество строк с пропусками в `days_employed`, шт.: 2162


Для того, чтобы проверить корректность работы собственной функции выполним аналогичные действия с помощью группировки данных по столбцу `income_type` методом `groupby()` и агрегирования.

In [32]:
# Группировка данных по столбцу `income_type` и агрегирование
data_grouped = data.groupby('income_type').agg({'days_employed': ['count', 'min', 'mean', 'median', 'max']})

# Выводим данные на экран
data_grouped

days_employed                                               \
                        count            min           mean         median   
income_type                                                                  
безработный                 2  337524.466835  366413.652744  366413.652744   
в декрете                   1   -3296.759962   -3296.759962   -3296.759962   
госслужащий              1307  -15193.032201   -3403.534603   -2689.137274   
компаньон                4550  -17615.563266   -2118.257358   -1555.947387   
пенсионер                3429  328728.720605  365025.091981  365286.622650   
предприниматель             1    -520.848083    -520.848083    -520.848083   
сотрудник                9949  -18388.949901   -2323.653522   -1572.328285   
студент                     1    -578.751554    -578.751554    -578.751554   

                                
                           max  
income_type                     
безработный      395302.838654  
в декрете         -3296.759962  
госслужащий         -39.954170  
компаньон           -30.195337  
пенсионер        401755.400475  
предприниматель    -520.848083  
сотрудник           -24.141633  
студент            -578.751554

**Промежуточный вывод:**

✅ функция `days_employed_info (data)` работает корректно.

##### Анализ аномальных значений в столбце `days_employed`

**Найденные артефакты (аномалии)** в столбце `days_employed`:
- Столбец содержит данные типа число с плавающей точкой, хотя по смыслу показателя должны быть целые числа.
- Почти 74% (15905 строк из 21525) содержат отрицательные значения. Особенно много их для категории типа занятости `сотрудник` (10014).
- Категории `пенсионер` и `безработный` содержат явно ошибочные значения (если исходить из условия, что в столбце приведено количество дней трудового стажа, то при пересчете в года получаются значения порядка 1000 лет).

**Возможные причины появления артефактов (аномалий)** в столбце `days_employed`:
- То, что в столбце хранятся числа с плавающей точкой говорит о том, что в столбце хранятся не те данные, которые заявлены (наиболее близкий к имеющимся данным результат дает гипотеза, что это трудовой стаж в неделях, а не днях).
- Отрицательные значения возможно возникли, если при расчете из даты начала работы вычитали дату завершения работы, а не наоборот.
- Аномально большие или малые значения в столбцах `пенсионер`, `безработный` и `сотрудник` возможно появились из-за ошибки при вводе года начала или завершения работы.

Поскольку величина трудового стажа по условию не участвует в ответе на поставленные вопросы и, принимая во внимание, что большой объём данных с некорректными значениями в этом столбце не позволяет просто удалить соответствующие строки из датасета (мы потерям 2/3 данных), то для дальнейшей работы мы:
1. Заменим все отрицательные значения в столбце `days_employed` на положительные.
1. После этого заполним пропуски медианными значениями в зависимости от категории типа занятости `income_type`.


##### Исправление аномальных значений в столбце `days_employed`

Задание 6. В данных могут встречаться артефакты (аномалии) — значения, которые не отражают действительность и появились по какой-то ошибке. Таким артефактом будет отрицательное количество дней трудового стажа в столбце `days_employed`. Для реальных данных это нормально. Обработайте значения в этом столбце: замените все отрицательные значения положительными с помощью метода `abs()`.

Задание 7. Для каждого типа занятости выведите медианное значение трудового стажа в днях из столбца `days_employed`. У двух типов (безработные и пенсионеры) получатся аномально большие значения. Исправить такие значения сложно, поэтому оставьте их как есть.

In [33]:
# Заменяем отрицательные значения в столбце `days_employed` на положительные
data['days_employed'] = data['days_employed'].abs()

# Проверяем результат замены с помощью функции days_employed_info (data)
days_employed_info(data)

income_type  negative  zero  positive            min           mean  \
0        сотрудник         0     0      9949      24.141633    2323.653522   
1        пенсионер         0     0      3429  328728.720605  365025.091981   
2        компаньон         0     0      4550      30.195337    2118.257358   
3      госслужащий         0     0      1307      39.954170    3403.534603   
4      безработный         0     0         2  337524.466835  366413.652744   
5  предприниматель         0     0         1     520.848083     520.848083   
6          студент         0     0         1     578.751554     578.751554   
7        в декрете         0     0         1    3296.759962    3296.759962   

          median            max   NaN  
0    1572.328285   18388.949901  1101  
1  365286.622650  401755.400475   410  
2    1555.947387   17615.563266   504  
3    2689.137274   15193.032201   146  
4  366413.652744  395302.838654     0  
5     520.848083     520.848083     1  
6     578.751554     578.751554     0  
7    3296.759962    3296.759962     0

Задание 11. Заполните пропуски в столбце `days_employed` медианными значениями по каждому типу занятости `income_type`. 

**Первоначальная версия проекта:** последовательное преобразование методом `.loc`.

In [34]:
# Произведем замену пропусков в столбце `days_employed` на соответствующие медианные для каждого типа занятости

# data.loc[(data['days_employed'].isna()) & (data['income_type'] == 'сотрудник'), "days_employed"] = data[data['income_type'] == 'сотрудник']['days_employed'].median()
# data.loc[(data['days_employed'].isna()) & (data['income_type'] == 'пенсионер'), "days_employed"] = data[data['income_type'] == 'пенсионер']['days_employed'].median()
# data.loc[(data['days_employed'].isna()) & (data['income_type'] == 'компаньон'), "days_employed"] = data[data['income_type'] == 'компаньон']['days_employed'].median()
# data.loc[(data['days_employed'].isna()) & (data['income_type'] == 'госслужащий'), "days_employed"] = data[data['income_type'] == 'госслужащий']['days_employed'].median()
# data.loc[(data['days_employed'].isna()) & (data['income_type'] == 'предприниматель'), "days_employed"] = data[data['income_type'] == 'предприниматель']['days_employed'].median()

# Проверяем результат заполнения пропусков
# days_employed_info (data)

**Поздняя версия проекта:** использование методов `fillna()`, `groupby()` и `.transform('median')`

In [35]:
# Замена пропусков в столбце `days_employed` на соответствующие медианные для каждого типа занятости 
data['days_employed'] = data['days_employed'].fillna(data.groupby('income_type')['total_income'].transform('median'))

# Проверяем результат заполнения пропусков
days_employed_info (data)

income_type  negative  zero  positive            min           mean  \
0        сотрудник         0     0     11050      24.141633   16299.951115   
1        пенсионер         0     0      3839  118514.486412  338698.093209   
2        компаньон         0     0      5054      30.195337   19095.068909   
3      госслужащий         0     0      1453      39.954170   18178.815057   
4      безработный         0     0         2  337524.466835  366413.652744   
5  предприниматель         0     0         2     520.848083  249841.996515   
6          студент         0     0         1     578.751554     578.751554   
7        в декрете         0     0         1    3296.759962    3296.759962   

          median            max  NaN  
0    1809.527317  142594.396847    0  
1  360632.255610  401755.400475    0  
2    1776.386087  172357.950966    0  
3    3040.268136  150447.935283    0  
4  366413.652744  395302.838654    0  
5  249841.996515  499163.144947    0  
6     578.751554     578.751554    0  
7    3296.759962    3296.759962    0

##### Вывод по подразделу 5.2.2

✅ Артефакты в столбце `days_employed` устранены.

[В начало подраздела](#Проверка-столбца-days_employed) | [В начало раздела](#Проверка-данных-на-аномалии-и-исправления) | [К содержанию проекта](#Содержание)

#### Проверка столбца `dob_years`

##### Поиск аномальных значений в столбце `dob_years`

In [36]:
# Выведем на экран все уникальные значения столбца `dob_years`
data['dob_years'].unique()

array([42, 36, 33, 32, 53, 27, 43, 50, 35, 41, 40, 65, 54, 56, 26, 48, 24,
       21, 57, 67, 28, 63, 62, 47, 34, 68, 25, 31, 30, 20, 49, 37, 45, 61,
       64, 44, 52, 46, 23, 38, 39, 51,  0, 59, 29, 60, 55, 58, 71, 22, 73,
       66, 69, 19, 72, 70, 74, 75], dtype=int64)

**Результат проверки:** в наборе значений столбца `dob_years` обнаружены аномальные значения: `0`.

##### Анализ аномальных значений в столбце `dob_years`

Сделаем обзор и оценим количество строк, содержащих данную аномалию.

In [37]:
# Фильтруем в новый датасет строки с нужным аномальным значением
dob_years_zero_data = data[data['dob_years'] == 0]

# Выводим на экран новый датасет полностью, чтобы оценить есть ли взаимосвязь аномальных значений с какими-то другими в датасете
display(dob_years_zero_data)
print(f'Всего строк с со значением `0` в столбце `dob_years`: {dob_years_zero_data.shape[0]}')
print(f'Доля строк с со значением `0` в столбце `dob_years` в датасете: {(dob_years_zero_data.shape[0] / data.shape[0]):.2%}')

children  days_employed  dob_years education  education_id  \
99            0  346541.618895          0   Среднее             1   
149           0    2664.273168          0   среднее             1   
270           3    1872.663186          0   среднее             1   
578           0  397856.565013          0   среднее             1   
1040          0    1158.029561          0    высшее             0   
...         ...            ...        ...       ...           ...   
19829         0  142594.396847          0   среднее             1   
20462         0  338734.868540          0   среднее             1   
20577         0  331741.271455          0   среднее             1   
21179         2     108.967042          0    высшее             0   
21313         0    1268.487728          0   среднее             1   

               family_status  family_status_id gender income_type  debt  \
99           женат / замужем                 0      F   пенсионер     0   
149                в разводе                 3      F   сотрудник     0   
270          женат / замужем                 0      F   сотрудник     0   
578          женат / замужем                 0      F   пенсионер     0   
1040               в разводе                 3      F   компаньон     0   
...                      ...               ...    ...         ...   ...   
19829        женат / замужем                 0      F   сотрудник     0   
20462        женат / замужем                 0      F   пенсионер     0   
20577  Не женат / не замужем                 4      F   пенсионер     0   
21179        женат / замужем                 0      M   компаньон     0   
21313  Не женат / не замужем                 4      M   сотрудник     0   

        total_income                                 purpose  
99      71291.522491                              автомобиль  
149     70176.435951                       операции с жильем  
270    102166.458894                            ремонт жилью  
578     97620.687042  строительство собственной недвижимости  
1040   303994.134987                         свой автомобиль  
...              ...                                     ...  
19829  142594.396847                                   жилье  
20462  259193.920299                    покупка своего жилья  
20577  129788.762899                            недвижимость  
21179  240702.007382        строительство жилой недвижимости  
21313  152419.184851                       операции с жильем  

[100 rows x 12 columns]

Всего строк с со значением `0` в столбце `dob_years`: 100
Доля строк с со значением `0` в столбце `dob_years` в датасете: 0.47%


**Выводы по результатам анализа аномальных значений в столбце `dob_years`**:
* Взаимосвязи между аномальными значениями в столбце `dob_years` и другими данными не выявлено. Таким образом, можно принять гипотезу об ошибочном вводе данных.
* Доля строк с ошибочными значениями в столбце `dob_years` относительно общего объёма датасета мала (0.47%). Таким образом, ни удаление этих строк из датасета, ни изменение их значений на условно правильные скорее всего не приведет к существенным искажениям данных на последующих шагах анализа.
* Исправим аномальные значения в этом столбце, заменив их на соответствующие медианные, рассчитанные для категорий `income_type`.

##### Исправление аномальных значений в столбце `dob_years`

In [38]:
# Рассчитаем медианные значения для каждого типа занятости
median_age_by_income_type = data.groupby('income_type')['dob_years'].median()

# Выводим полученные значения медиан на экран
median_age_by_income_type

income_type
безработный        38.0
в декрете          39.0
госслужащий        40.0
компаньон          39.0
пенсионер          60.0
предприниматель    42.5
сотрудник          39.0
студент            22.0
Name: dob_years, dtype: float64

**Первоначальная версия проекта:** последовательное преобразование методом `.loc`.

In [39]:
# Произведем замену нулевых значений в столбце `dob_years` на соответствующие медианные для каждого типа занятости

# Заполнение пропусков в категории 'сотрудник' медианными значениями
#data.loc[(data['dob_years'] == 0) & (data['income_type'] == 'сотрудник'), 'dob_years'] = 39

# Заполнение пропусков в категории 'пенсионер' медианными значениями
#data.loc[(data['dob_years'] == 0) & (data['income_type'] == 'пенсионер'), 'dob_years'] = 60

# Заполнение пропусков в категории 'компаньон' медианными значениями
#data.loc[(data['dob_years'] == 0) & (data['income_type'] == 'компаньон'), 'dob_years'] = 39

# Заполнение пропусков в категории 'госслужащий' медианными значениями
#data.loc[(data['dob_years'] == 0) & (data['income_type'] == 'госслужащий'), 'dob_years'] = 40

# Заполнение пропусков в категории 'предприниматель' медианными значениями
#data.loc[(data['dob_years'] == 0) & (data['income_type'] == 'предприниматель'), 'dob_years'] = 42.5

# Заполнение пропусков в категории 'безработный' медианными значениями
#data.loc[(data['dob_years'] == 0) & (data['income_type'] == 'безработный'), 'dob_years'] = 38

# Заполнение пропусков в категории 'студент' медианными значениями
#data.loc[(data['dob_years'] == 0) & (data['income_type'] == 'студент'), 'dob_years'] = 22

# Заполнение пропусков в категории 'в декрете' медианными значениями
#data.loc[(data['dob_years'] == 0) & (data['income_type'] == 'в декрете'), 'dob_years'] = 39

# Проверка преобразования - выводим на экран уникальные значения `dob_years`
#data['dob_years'].unique()

**Поздняя версия проекта:** использование собственной фукнции `replace_zero_age(row)`.

In [40]:
# Функция для замены нулевых значений 'dob_years' на медианные значения по 'income_type'
def replace_zero_age(row):
    if row['dob_years'] == 0:
        return median_age_by_income_type[row['income_type']]
    return row['dob_years']

# Применяем функцию к датафрейму для замены нулевых значений
data['dob_years'] = data.apply(replace_zero_age, axis=1)

# Проверяем рузультат работы функции
data['dob_years'].unique()

array([42., 36., 33., 32., 53., 27., 43., 50., 35., 41., 40., 65., 54.,
       56., 26., 48., 24., 21., 57., 67., 28., 63., 62., 47., 34., 68.,
       25., 31., 30., 20., 49., 37., 45., 61., 64., 44., 52., 46., 23.,
       38., 39., 51., 60., 59., 29., 55., 58., 71., 22., 73., 66., 69.,
       19., 72., 70., 74., 75.])

##### Вывод по подразделу 5.2.3

✅ Артефакты в столбце `dob_years` устранены.

[В начало подраздела](#Проверка-столбца-dob_years) | [В начало раздела](#Проверка-данных-на-аномалии-и-исправления) | [К содержанию проекта](#Содержание)

#### Проверка столбца `education`

##### Поиск аномальных значений в столбце `education`

In [41]:
# Выведем на экран все уникальные значения столбца `education`
data['education'].unique()

array(['высшее', 'среднее', 'Среднее', 'СРЕДНЕЕ', 'ВЫСШЕЕ',
       'неоконченное высшее', 'начальное', 'Высшее',
       'НЕОКОНЧЕННОЕ ВЫСШЕЕ', 'Неоконченное высшее', 'НАЧАЛЬНОЕ',
       'Начальное', 'Ученая степень', 'УЧЕНАЯ СТЕПЕНЬ', 'ученая степень'],
      dtype=object)

**Результат проверки:** в наборе значений столбца `education` обнаружены аномальные значения: в наименованиях категорий образования используются строчные и прописные буквы из-за чего возникает дублирование категорий при категоризации данных по этому параметру. Для исправления этого сделаем все значения в этом столбце строчными.

##### Исправление аномальных значений в столбце `education`

Задание 14. Обработайте неявные дубликаты в столбце `education`. В этом столбце есть одни и те же значения, но записанные по-разному: с использованием заглавных и строчных букв. Приведите их к нижнему регистру.

In [42]:
# Приводим все значения в столбце `education` к нижнему регистру
data['education'] = data['education'].str.lower()

# Проверяем результат
data['education'].unique()

array(['высшее', 'среднее', 'неоконченное высшее', 'начальное',
       'ученая степень'], dtype=object)

##### Вывод по подразделу 5.2.4

✅ Артефакты в столбце `education` устранены.

[В начало подраздела](#Проверка-столбца-education) | [В начало раздела](#Проверка-данных-на-аномалии-и-исправления) | [К содержанию проекта](#Содержание)

#### Проверка столбца `education_id`

##### Поиск аномальных значений в столбце `education_id`

In [43]:
# Выведем на экран все уникальные значения столбца `education_id`
data['education_id'].unique()

array([0, 1, 2, 3, 4], dtype=int64)

**Результат проверки:** в наборе значений столбца `education_id` не обнаружены аномальные значения, количество значений — 5 соответствует количеству истинно уникальных категорий в столбце `education` (ранее, при [обзоре датасета](#Выводы-по-разделу) было выявлено 3 категории):
* `education_id = 0` - высшее;
* `education_id = 1` - среднее;
* `education_id = 2` - неоконченное высшее.

Дополнительно требуется установить соответствие между оставшимися значениями `education_id` (3 и 4) и категориями `начальное` и `ученая степень`. Для этого отфильтруем датасет по соответствующим значениями столбца `education_id` и выведем на экран соответствующие строки.

In [44]:
# Выводим на экран строки датасета c `education_id = 3, 4`, чтобы узнать соответствующее значение в столбце `education`
display(data[data['education_id'] == 3].head(1))
data[data['education_id'] == 4].head(1)

children  days_employed  dob_years  education  education_id  \
31         0    1682.083438       47.0  начальное             3   

      family_status  family_status_id gender income_type  debt   total_income  \
31  женат / замужем                 0      F   сотрудник     0  275485.684538   

   purpose  
31   жилье

children  days_employed  dob_years       education  education_id  \
2963         0   337584.81556       69.0  ученая степень             4   

        family_status  family_status_id gender income_type  debt  \
2963  женат / замужем                 0      M   пенсионер     0   

      total_income                     purpose  
2963  98752.495442  покупка жилой недвижимости

##### Выводы по подразделу 5.2.5

✅ Артефакты в столбце `education_id` отсутствуют.

Полный набор значений в столбце `education` для соответствующих `education_id` выглядит так:
- `education_id = 0` - высшее;
- `education_id = 1` - среднее;
- `education_id = 2` - неоконченное высшее;
- `education_id = 3` - начальное;
- `education_id = 4` - ученая степень.

[В начало подраздела](#Проверка-столбца-education_id) | [В начало раздела](#Проверка-данных-на-аномалии-и-исправления) | [К содержанию проекта](#Содержание)

#### Проверка столбца `family_status`

##### Поиск аномальных значений в столбце `family_status`

In [45]:
# Выведем на экран все уникальные значения столбца `family_status`
data['family_status'].unique()

array(['женат / замужем', 'гражданский брак', 'вдовец / вдова',
       'в разводе', 'Не женат / не замужем'], dtype=object)

**Результат проверки:** в наборе значений столбца `family_status` не обнаружены аномальные значения. Следует заменить прописную букву строчной в значениях `Не женат / не замужем`.

##### Исправление аномальных значений в столбце `family_status`

In [46]:
# Приводим все значения столбца `family_status` к нижнему регистру
data['family_status'] = data['family_status'].str.lower()

# Проверяем результат преобразования
data['family_status'].unique()

array(['женат / замужем', 'гражданский брак', 'вдовец / вдова',
       'в разводе', 'не женат / не замужем'], dtype=object)

##### Вывод по подразделу 5.2.6

✅ Артефакты в столбце `family_status` отсутствуют.

[В начало подраздела](#Проверка-столбца-family_status) | [В начало раздела](#Проверка-данных-на-аномалии-и-исправления) | [К содержанию проекта](#Содержание)

#### Проверка столбца `family_status_id`

##### Поиск аномальных значений в столбце `family_status_id`

In [47]:
# Выведем на экран все уникальные значения столбца `family_status_id`
data['family_status_id'].unique()

array([0, 1, 2, 3, 4], dtype=int64)

**Результат проверки:** в наборе значений столбца `family_status_id` не обнаружены аномальные значения, количество значений — 5 соответствует количеству истинно уникальных категорий в столбце `family_status` (ранее, при [обзоре датасета](#Выводы-по-разделу) было выявлено 2 категории):
* `family_status_id = 0` - женат / замужем;
* `family_status_id = 1` - гражданский брак;

Дополнительно требуется установить соответствие между оставшимися значениями `family_status_id` (2, 3 и 4) и категориями `вдовец / вдова`, `в разводе` и `Не женат / не замужем`.

In [48]:
# Выводим на экран строки датасета c `family_status_id = 2, 3, 4`, чтобы узнать соответствующее значение в столбце `family_status`
display(data[data['family_status_id'] == 2].head(1))
display(data[data['family_status_id'] == 3].head(1))
data[data['family_status_id'] == 4].head(1)

children  days_employed  dob_years education  education_id  \
18         0  400281.136913       53.0   среднее             1   

     family_status  family_status_id gender income_type  debt  total_income  \
18  вдовец / вдова                 2      F   пенсионер     0  56823.777243   

                               purpose  
18  на покупку подержанного автомобиля

children  days_employed  dob_years education  education_id family_status  \
19         0   10038.818549       48.0   среднее             1     в разводе   

    family_status_id gender income_type  debt   total_income  \
19                 3      F   сотрудник     0  242831.107982   

                         purpose  
19  на покупку своего автомобиля

children  days_employed  dob_years education  education_id  \
24         1  338551.952911       57.0   среднее             1   

            family_status  family_status_id gender income_type  debt  \
24  не женат / не замужем                 4      F   пенсионер     0   

     total_income                                purpose  
24  290547.235997  операции с коммерческой недвижимостью

##### Выводы по подразделу 5.2.7

✅ Артефакты в столбце `family_status_id` отсутствуют.

Полный набор значений в столбце `family_status` для соответствующих `family_status_id` выглядит так:
* `family_status_id = 0` - женат / замужем;
* `family_status_id = 1` - гражданский брак;
* `family_status_id = 2` - вдовец / вдова;
* `family_status_id = 3` - в разводе;
* `family_status_id = 4` - Не женат / не замужем.

[В начало подраздела](#Проверка-столбца-family_status_id) | [В начало раздела](#Проверка-данных-на-аномалии-и-исправления) | [К содержанию проекта](#Содержание)

#### Проверка столбца `gender`

##### Поиск аномальных значений в столбце `gender`

In [49]:
# Выведем на экран все уникальные значения столбца `gender`
data['gender'].unique()

array(['F', 'M', 'XNA'], dtype=object)

**Результат проверки:** в наборе значений столбца `gender` обнаружены `XNA`. Необходимо выяснить, что они значат.

##### Анализ аномальных значений в столбце `gender`

In [50]:
# Фильтруем в новый датасет строки со значением `gender = XNA`
gender_XNA = data[data['gender'] == 'XNA']

# Выводим на экран строку полученного датасета, чтобы узнать соответствующее значение в столбце `education`
gender_XNA

children  days_employed  dob_years            education  education_id  \
10701         0    2358.600502       24.0  неоконченное высшее             2   

          family_status  family_status_id gender income_type  debt  \
10701  гражданский брак                 1    XNA   компаньон     0   

        total_income               purpose  
10701  203905.157261  покупка недвижимости

**Вывод**

В датасете содержится всего одна строка, содержащая некорректное значение столбца `gender`. Её исключение не окажет существенного влияния на результат исследования.

##### Исправление аномальных значений в столбце `gender`

In [51]:
# Удаляем из датафрейма строку с аномальным значением
data = data[data['gender'] != 'XNA']

# Проверяем результат преобразования
data['gender'].unique()

array(['F', 'M'], dtype=object)

##### Выводы по подразделу 5.2.8

✅ Артефакты в столбце `gender` устранены.

[В начало подраздела](#Проверка-столбца-gender) | [В начало раздела](#Проверка-данных-на-аномалии-и-исправления) | [К содержанию проекта](#Содержание)

#### Проверка столбца `income_type`

##### Поиск аномальных значений в столбце `income_type`

Проверка столбца `income_type` была проведена ранее (см. [пп. 5.1.3.1](#Получение-уникальных-значений-в-столбце-income_type)).

##### Выводы по подразделу 5.2.9

✅ Артефакты в столбце `income_type` отсутствуют.

[В начало подраздела](#Проверка-столбца-income_type) | [В начало раздела](#Проверка-данных-на-аномалии-и-исправления) | [К содержанию проекта](#Содержание)

#### Проверка столбца `debt`

##### Поиск аномальных значений в столбце `debt`

In [52]:
# Выведем на экран все уникальные значения столбца `debt`
data['debt'].unique()

array([0, 1], dtype=int64)

**Результат проверки:** в наборе значений столбца `debt` не обнаружены аномальные значения.

##### Вывод по подразделу 5.2.10

✅ Артефакты в столбце `debt` отсутствуют.

[В начало подраздела](#Проверка-столбца-debt) | [В начало раздела](#Проверка-данных-на-аномалии-и-исправления) | [К содержанию проекта](#Содержание)

#### Проверка столбца `total_income`

##### Поиск аномальных значений в столбце `total_income`

Ранее в [пп. 5.1.1](#Нахождение-пропусков) были выявлены пропуски в столбце `total_income` и заполнены медианными значениями в соответствии с типом занятости (см. [пп. 5.1.3](#Заполнение-пропусков-в-столбце-total_income)).


##### Вывод по подразделу 5.2.11

✅ Артефакты в столбце `total_income` отсутствуют.

[В начало подраздела](#Проверка-столбца-total_income) | [В начало раздела](#Проверка-данных-на-аномалии-и-исправления) | [К содержанию проекта](#Содержание)

#### Проверка столбца `purpose`

##### Поиск аномальных значений в столбце `purpose`

Задание 17. Выведите на экран перечень уникальных целей взятия кредита из столбца `purpose`.

In [53]:
# Выведем на экран все уникальные значения столбца `purpose`
data['purpose'].unique()

array(['покупка жилья', 'приобретение автомобиля',
       'дополнительное образование', 'сыграть свадьбу',
       'операции с жильем', 'образование', 'на проведение свадьбы',
       'покупка жилья для семьи', 'покупка недвижимости',
       'покупка коммерческой недвижимости', 'покупка жилой недвижимости',
       'строительство собственной недвижимости', 'недвижимость',
       'строительство недвижимости', 'на покупку подержанного автомобиля',
       'на покупку своего автомобиля',
       'операции с коммерческой недвижимостью',
       'строительство жилой недвижимости', 'жилье',
       'операции со своей недвижимостью', 'автомобили',
       'заняться образованием', 'сделка с подержанным автомобилем',
       'получение образования', 'автомобиль', 'свадьба',
       'получение дополнительного образования', 'покупка своего жилья',
       'операции с недвижимостью', 'получение высшего образования',
       'свой автомобиль', 'сделка с автомобилем',
       'профильное образование', 'высшее об

**Результат проверки:** в наборе значений столбца `purpose` выявлены множественные неявные повторы (напр. 'покупка жилья', 'операции с жильем', 'покупка жилья для семьи' и т. д.).


##### Выводы по подразделу 5.2.12

✅ В столбце `purpose` содержатся множественные неявные повторы. Требуется категоризировать данные этого столбца по укрупнённым категориям, чтобы они не искажали анализ данных.

[В начало подраздела](#Проверка-столбца-purpose) | [В начало раздела](#Проверка-данных-на-аномалии-и-исправления) | [К содержанию проекта](#Содержание)

### Изменение типов данных

#### Замена типа данных в столбце `total_income`

Задание 13. Замените вещественный тип данных в столбце `total_income` на целочисленный с помощью метода `astype()`.

In [54]:
# Заменяем вещественный тип данных в столбце `total_income` на целочисленный c помощью метода astype()
data['total_income'] = data['total_income'].astype('int')

# Проверяем результат преобразования
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 21401 entries, 0 to 21524
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   children          21401 non-null  int64  
 1   days_employed     21401 non-null  float64
 2   dob_years         21401 non-null  float64
 3   education         21401 non-null  object 
 4   education_id      21401 non-null  int64  
 5   family_status     21401 non-null  object 
 6   family_status_id  21401 non-null  int64  
 7   gender            21401 non-null  object 
 8   income_type       21401 non-null  object 
 9   debt              21401 non-null  int64  
 10  total_income      21401 non-null  int32  
 11  purpose           21401 non-null  object 
dtypes: float64(2), int32(1), int64(4), object(5)
memory usage: 2.0+ MB


#### Вывод по подразделу 5.3

✅ Вещественный тип данных в столбце `total_income` успешно заменен на целочисленный.

[В начало подраздела](#Замена-типа-данных-в-столбце-total_income) | [В начало раздела](#Изменение-типов-данных) | [К содержанию проекта](#Содержание)

### Удаление строк-дубликатов в данных

Задание 15. Выведите на экран количество строк-дубликатов в данных. Если такие строки присутствуют, удалите их. Сбрасывать индексы после удаления строк дубликатов с помощью `reset_index(drop=True)` здесь не требуется.

#### Поиск строк-дубликатов в данных

In [55]:
# Выводим на экран количество строк-дубликатов в данных
print('Обнаружено явных дубликатов в датафрейме:', data.duplicated().sum())

# Находим долю строк-дубликатов от общего количества строк в датасете
duplicated_share = data.duplicated().sum() / len(data)

# Выводим на экран долю строк-дубликатов от общего количества строк в датасете 
print(f'Доля строк-дубликатов от общего количества строк в датасете: {duplicated_share:.4%}')

Обнаружено явных дубликатов в датафрейме: 71
Доля строк-дубликатов от общего количества строк в датасете: 0.3318%


**Результат проверки:** в датафрейме выявлено всего 71 строк-дубликатов, что составляет 0,33% от объёма данных. Строки-дубликаты могут быть удалены, так как это не окажет существенного влияния на анализ данных.

#### Удаление строк-дубликатов в данных

In [56]:
# Удаляем явные дубликаты
data = data.drop_duplicates()

#### Вывод по подразделу 5.4

✅ Датафрейм очищен от строк-дубликатов.

[В начало раздела](#Удаление-строк-дубликатов-в-данных) | [К содержанию проекта](#Содержание)

### Декомпозиция исходного датафрейма. Формирование дополнительных датафреймов словарей

#### Уточнение значений категорий содержащихся в столбцах `education` и `family_status`

In [57]:
data['education'].value_counts().head(15)

среднее                15075
высшее                  5227
неоконченное высшее      740
начальное                282
ученая степень             6
Name: education, dtype: int64

In [58]:
data['family_status'].value_counts().head(15)

женат / замужем          12261
гражданский брак          4133
не женат / не замужем     2796
в разводе                 1189
вдовец / вдова             951
Name: family_status, dtype: int64

Неявные дубликаты в этих столбцах были удалены нами ранее (см. пп. [5.2.4.2](#Исправление-аномальных-значений-в-столбце-education) и [5.2.6.2](#Исправление-аномальных-значений-в-столбце-family_status))

#### Создание датафреймов "словарей" для хранения категорий `education` и `family_status`

In [59]:
# "Вырезаем" из исходного датафрейма столбцы 'education_id','education'
# и формируем из них новый датафрем "словарь"
education_dict = data[['education_id','education']]

# Удаляем из созданного "словаря" повторяющиеся значения
education_dict = education_dict.drop_duplicates().reset_index(drop=True)

# Проверяем результат
education_dict

education_id            education
0             0               высшее
1             1              среднее
2             2  неоконченное высшее
3             3            начальное
4             4       ученая степень

In [60]:
# "Вырезаем" из исходного датафрейма столбцы 'family_status_id','family_status'
# и формируем из них новый датафрем "словарь"
family_status_dict = data[['family_status_id','family_status']]

# Удаляем из созданного "словаря" повторяющиеся значения
family_status_dict = family_status_dict.drop_duplicates().reset_index(drop=True)

# проверяем результат
family_status_dict

family_status_id          family_status
0                 0        женат / замужем
1                 1       гражданский брак
2                 2         вдовец / вдова
3                 3              в разводе
4                 4  не женат / не замужем

#### Удаление столбцов `education` и `family_status` из исходного датафрейма

In [61]:
# Удаляем столбцы из датафрейма
data = data.drop(['education', 'family_status'], axis=1)

# Проверяем результат удаления
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 21330 entries, 0 to 21524
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   children          21330 non-null  int64  
 1   days_employed     21330 non-null  float64
 2   dob_years         21330 non-null  float64
 3   education_id      21330 non-null  int64  
 4   family_status_id  21330 non-null  int64  
 5   gender            21330 non-null  object 
 6   income_type       21330 non-null  object 
 7   debt              21330 non-null  int64  
 8   total_income      21330 non-null  int32  
 9   purpose           21330 non-null  object 
dtypes: float64(2), int32(1), int64(4), object(3)
memory usage: 1.7+ MB


#### Вывод по подразделу 5.5

✅ Созданы датафреймы-словари `education_dict` и `family_status_dict` которые можно использовать как справочники для основной таблицы, связанные с ней по полю-идентификатору соответствующего статуса. Это позволило очистить исходный датасет от неиспользуемых в анализе данных и сделать его более компактным и удобным для анализа.

[В начало раздела](#Декомпозиция-исходного-датафрейма.-Формирование-дополнительных-датафреймов-словарей) | [К содержанию проекта](#Содержание)

### Категоризация дохода

Задание 16. На основании диапазонов, указанных ниже, создайте в датафрейме `data` столбец `total_income_category` с категориями:
- 0–30000 — `'E'`;
- 30001–50000 — `'D'`;
- 50001–200000 — `'C'`;
- 200001–1000000 — `'B'`;
- 1000001 и выше — `'A'`.

</br></br>
Например, кредитополучателю с доходом 25000 нужно назначить категорию `'E'`, а клиенту, получающему 235000, — `'B'`.

#### Создание функции `set_income_category`

In [62]:
# Создаем функцию для категоризации дохода
def set_income_category(row):
    total_income = row['total_income']
    if total_income <= 30000 and total_income >= 0:
        return 'E'
    if total_income <= 50000 and total_income >= 30001:
        return 'D'
    if total_income <= 200000 and total_income >= 50001:
        return 'C'
    if total_income <= 1000000 and total_income >= 200001:
        return 'B'
    if total_income > 1000001:
        return 'A'

#### Добавление в датафрейм столбца с категорией дохода

In [63]:
# Добавляем в исходный датафрейм столбец с категориями дохода
data['total_income_category'] = data.apply(set_income_category, axis=1)

# Проверяем результат
data.head()

children  days_employed  dob_years  education_id  family_status_id gender  \
0         1    8437.673028       42.0             0                 0      F   
1         1    4024.803754       36.0             1                 0      F   
2         0    5623.422610       33.0             1                 0      M   
3         3    4124.747207       32.0             1                 0      M   
4         0  340266.072047       53.0             1                 1      F   

  income_type  debt  total_income                     purpose  \
0   сотрудник     0        253875               покупка жилья   
1   сотрудник     0        112080     приобретение автомобиля   
2   сотрудник     0        145885               покупка жилья   
3   сотрудник     0        267628  дополнительное образование   
4   пенсионер     0        158616             сыграть свадьбу   

  total_income_category  
0                     B  
1                     C  
2                     C  
3                     B  
4                     C

#### Вывод по подразделу 5.6

✅ Создана функция `set_income_category` с помощью которой в датафрейм добавляется столбец `total_income_category` с категориями дохода.

[В начало раздела](#Категоризация-дохода) | [К содержанию проекта](#Содержание)

### Категоризация целей кредита

Задание 18. Создайте функцию, которая на основании данных из столбца `purpose` сформирует новый столбец `purpose_category`, куда войдут следующие категории:
- `'операции с автомобилем'`,
- `'операции с недвижимостью'`,
- `'проведение свадьбы'`,
- `'получение образования'`.

</br></br>
Например, если в столбце purpose находится подстрока `'на покупку автомобиля'`, то в столбце `purpose_category` должна появиться строка `'операции с автомобилем'`.

Используйте собственную функцию с именем `categorize_purpose()` и метод `apply()`. Изучите данные в столбце `purpose` и определите, какие подстроки помогут вам правильно определить категорию.

#### Изучение столбца `purpose` и выделение подстрок для определения категории

По результатам проверки столбца `purpose` (см. [пп. 5.2.12](#Проверка-столбца-purpose)) были сформированы наборы уникальных значений целей кредитования для группировки по 4 основным категориям, приведённые в таблице:

<table style = "width: 100%; margin-bottom: 20px; border: 1px solid #dddddd; border-collapse: collapse">
    <thead style = "background: #efefef; border: 1px solid #dddddd">
        <tr>
            <th style = "width: 25%; text-align: center">Категория</th>
            <th style = "text-align: center">Значения в столбце 'purpose'</th>
        </tr>    
    </thead>
    <tbody>
        <tr>
            <td style = "text-align: left">операции с автомобилем</td>
            <td style = "text-align: left">'приобретение автомобиля', 'на покупку подержанного автомобиля', 'на покупку своего автомобиля', 'автомобили', 'сделка с подержанным автомобилем', 'автомобиль', 'свой автомобиль', 'сделка с автомобилем', 'на покупку автомобиля'</td>
        </tr>
        <tr>
            <td style = "text-align: left">операции с недвижимостью</td>
            <td style = "text-align: left">'покупка жилья', 'операции с жильем', 'покупка жилья для семьи', 'покупка недвижимости', 'покупка коммерческой недвижимости', 'покупка жилой недвижимости', 'строительство собственной недвижимости', 'недвижимость', 'строительство недвижимости', 'операции с коммерческой недвижимостью', 'строительство жилой недвижимости', 'жилье', 'операции со своей недвижимостью', 'покупка своего жилья', 'операции с недвижимостью', 'покупка жилья для сдачи', 'ремонт жилью'</td>
    </tr>
    <tr>
      <td style = "text-align: left">проведение свадьбы</td>
      <td style = "text-align: left">'сыграть свадьбу', 'на проведение свадьбы', 'свадьба'</td>
    </tr>    
    <tr>
      <td style = "text-align: left">получение образования</td>
      <td style = "text-align: left">'дополнительное образование', 'образование', 'заняться образованием', 'получение образования', 'получение дополнительного образования', 'получение высшего образования', 'профильное образование', 'высшее образование', 'заняться высшим образованием'</td>
    </tr>
    </tbody>    
</table>


На основании этих наборов сформируем список ключевых слов, по которым с помощью функции будем разделять исходный датафрейм по категориям целей кредитования:

<table style = "width: 100%; margin-bottom: 20px; border: 1px solid #dddddd; border-collapse: collapse">
    <thead style = "background: #efefef; border: 1px solid #dddddd">
        <tr>
            <th style = "width: 25%; text-align: center">Категория</th>
            <th style = "text-align: center">Подстрока</th>
        </tr>    
    </thead>
    <tbody>
        <tr>
            <td style = "text-align: left">операции с автомобилем</td>
            <td style = "text-align: left">"автомобил"</td>
        </tr>
        <tr>
            <td style = "text-align: left">операции с недвижимостью</td>
            <td style = "text-align: left">"жил" и "недвиж"</td>
    </tr>
    <tr>
      <td style = "text-align: left">проведение свадьбы</td>
      <td style = "text-align: left">"свадьб"</td>
    </tr>    
    <tr>
      <td style = "text-align: left">получение образования</td>
      <td style = "text-align: left">"образ"</td>
    </tr>
    </tbody>    
</table>

#### Функция для категоризации целей кредитования по ключевым словам

In [64]:
# Создаем функцию для категоризации целей кредитования
def purpose_category(list):
    if "автомобил" in list:
        return "операции с автомобилем"
    if "жил" in list or "недвиж" in list:
        return "операции с недвижимостью"
    if "свадьб" in list:
        return "проведение свадьбы"
    if "образ" in list:
        return "получение образования"

#### Категоризация датафрейма по целям кредитования

In [65]:
# Добавляем в исходный датафрейм столбец с категориями целей кредитования
data['purpose_category'] = data['purpose'].apply(purpose_category)

# Проверяем результат
data.head()

children  days_employed  dob_years  education_id  family_status_id gender  \
0         1    8437.673028       42.0             0                 0      F   
1         1    4024.803754       36.0             1                 0      F   
2         0    5623.422610       33.0             1                 0      M   
3         3    4124.747207       32.0             1                 0      M   
4         0  340266.072047       53.0             1                 1      F   

  income_type  debt  total_income                     purpose  \
0   сотрудник     0        253875               покупка жилья   
1   сотрудник     0        112080     приобретение автомобиля   
2   сотрудник     0        145885               покупка жилья   
3   сотрудник     0        267628  дополнительное образование   
4   пенсионер     0        158616             сыграть свадьбу   

  total_income_category          purpose_category  
0                     B  операции с недвижимостью  
1                     C    операции с автомобилем  
2                     C  операции с недвижимостью  
3                     B     получение образования  
4                     C        проведение свадьбы

#### Вывод по подразделу 5.7

✅ Создана функция `purpose_category` с помощью которой в датафрейм добавляется столбец `purpose_category` с категориями целей кредитования.

[В начало раздела](#Категоризация-целей-кредита) | [К содержанию проекта](#Содержание)

## Ответы на вопросы

### Вопрос 1

Задание 19. Есть ли зависимость между количеством детей и возвратом кредита в срок?

#### Вариант 1 (первоначальный, после ревью)

In [66]:
# Группируем данные для анализа в сводную таблицу
data_pivot_1 = data.pivot_table(index=['debt'], columns='children', values='family_status_id', aggfunc='count')

# Выводим результат на экран
display(data_pivot_1)

# Выводим процент невозвратов
for i in range(len(data['children'].unique())):
    print(f'Количество детей: {i} |', f'Процент невозвратов: {(data_pivot_1[i][1] / data_pivot_1[i][0]):.2%}')

children        0       1       2      3     4    5
debt                                               
0         13027.0  4364.0  1858.0  303.0  37.0  9.0
1          1063.0   444.0   194.0   27.0   4.0  NaN

Количество детей: 0 | Процент невозвратов: 8.16%
Количество детей: 1 | Процент невозвратов: 10.17%
Количество детей: 2 | Процент невозвратов: 10.44%
Количество детей: 3 | Процент невозвратов: 8.91%
Количество детей: 4 | Процент невозвратов: 10.81%
Количество детей: 5 | Процент невозвратов: nan%


#### Вариант 2 (после прохождения курса)

In [67]:
# Группируем данные для анализа в сводную таблицу
pivot_1 = data.pivot_table(index='debt',
                           columns='children',
                           values='family_status_id',
                           aggfunc='count')

# Добавляем строку с расчетом процента просрочек
pivot_1.loc['ratio'] = ((pivot_1.loc[1] / pivot_1.loc[0]) * 100).round(2)

# Выводим сводную таблицу на экран
pivot_1

children         0        1        2       3      4    5
debt                                                    
0         13027.00  4364.00  1858.00  303.00  37.00  9.0
1          1063.00   444.00   194.00   27.00   4.00  NaN
ratio         8.16    10.17    10.44    8.91  10.81  NaN

#### Ответ на вопрос 1

С ростом количества детей в семье процент невозвратов (отношение количества клиентов имеющих просрочку к количеству не имеющих задолженности по кредиту) растет.

[В начало подраздела](#Вопрос-1) | [В начало раздела](#Ответы-на-вопросы) | [К содержанию проекта](#Содержание)

### Вопрос 2

Задание 20. Есть ли зависимость между семейным положением и возвратом кредита в срок?

#### Вариант 1 (первоначальный, после ревью)

In [68]:
# Группируем данные для анализа в сводную таблицу
data_pivot_2 = data.pivot_table(index=['debt'], columns='family_status_id', values='dob_years', aggfunc='count')

# Выводим результат на экран
display(data_pivot_2)

# Выводим процент невозвратов
for i in range(len(data['family_status_id'].unique())):
    print('Семейное положение:', family_status_dict['family_status'][i],'|',f'Процент невозвратов: {(data_pivot_2[i][1] / data_pivot_2[i][0]):.2%}')

family_status_id      0     1    2     3     4
debt                                          
0                 11334  3748  888  1105  2523
1                   927   385   63    84   273

Семейное положение: женат / замужем | Процент невозвратов: 8.18%
Семейное положение: гражданский брак | Процент невозвратов: 10.27%
Семейное положение: вдовец / вдова | Процент невозвратов: 7.09%
Семейное положение: в разводе | Процент невозвратов: 7.60%
Семейное положение: не женат / не замужем | Процент невозвратов: 10.82%


#### Вариант 2 (после прохождения курса)

In [69]:
# Группируем данные для анализа в сводную таблицу
pivot_2 = data.pivot_table(index='debt',
                           columns='family_status_id',
                           values='dob_years',
                           aggfunc='count')

# Добавляем строку с расчетом процента просрочек
pivot_2.loc['ratio'] = ((pivot_2.loc[1] / pivot_2.loc[0]) * 100).round(2)

# Выводим сводную таблицу на экран
pivot_2 

family_status_id         0        1       2       3        4
debt                                                        
0                 11334.00  3748.00  888.00  1105.0  2523.00
1                   927.00   385.00   63.00    84.0   273.00
ratio                 8.18    10.27    7.09     7.6    10.82

#### Ответ на вопрос 2

Процент просрочки по кредитам выше среди холостых и живущих в гражданском браке.

[В начало подраздела](#Вопрос-2) | [В начало раздела](#Ответы-на-вопросы) | [К содержанию проекта](#Содержание)

### Вопрос 3

Задание 21. Есть ли зависимость между уровнем дохода и возвратом кредита в срок?

#### Вариант 1 (первоначальный, после ревью)

In [70]:
# Группируем данные для анализа в сводную таблицу 
data_pivot_3 = data.pivot_table(index=['debt'], columns='total_income_category', values='dob_years', aggfunc='count')

# Выводим результат на экран
display(data_pivot_3)

# Выводим процент невозвратов
income_1 = data_pivot_3['A'][1] / data_pivot_3['A'][0]
income_2 = data_pivot_3['B'][1] / data_pivot_3['B'][0]
income_3 = data_pivot_3['C'][1] / data_pivot_3['C'][0]
income_4 = data_pivot_3['D'][1] / data_pivot_3['D'][0]
income_5 = data_pivot_3['E'][1] / data_pivot_3['E'][0]

print(f'Уровень дохода: A (> 1000001) |', f'Процент невозвратов: {income_1:.2%}')
print(f'Уровень дохода: B (200001–1000000) |', f'Процент невозвратов: {income_2:.2%}')
print(f'Уровень дохода: C (50001–200000) |', f'Процент невозвратов: {income_3:.2%}')
print(f'Уровень дохода: D (30001–50000) |', f'Процент невозвратов: {income_4:.2%}')
print(f'Уровень дохода: E (0–30000) |', f'Процент невозвратов: {income_5:.2%}')

total_income_category   A     B      C    D   E
debt                                           
0                      23  4659  14568  328  20
1                       2   354   1353   21   2

Уровень дохода: A (> 1000001) | Процент невозвратов: 8.70%
Уровень дохода: B (200001–1000000) | Процент невозвратов: 7.60%
Уровень дохода: C (50001–200000) | Процент невозвратов: 9.29%
Уровень дохода: D (30001–50000) | Процент невозвратов: 6.40%
Уровень дохода: E (0–30000) | Процент невозвратов: 10.00%


#### Вариант 2 (после прохождения курса)

In [71]:
# Группируем данные для анализа в сводную таблицу
pivot_3 = data.pivot_table(index='debt',
                           columns='total_income_category',
                           values='dob_years',
                           aggfunc='count')

# Добавляем строку с расчетом процента просрочек
pivot_3.loc['ratio'] = ((pivot_3.loc[1] / pivot_3.loc[0]) * 100).round(2)

# Выводим сводную таблицу на экран
pivot_3 

total_income_category     A       B         C      D     E
debt                                                      
0                      23.0  4659.0  14568.00  328.0  20.0
1                       2.0   354.0   1353.00   21.0   2.0
ratio                   8.7     7.6      9.29    6.4  10.0

#### Ответ на вопрос 3

Процент невозвратов наибольший у группы с доходом до 30000 руб. и у группы с уровнем дохода от 50001–200000. Скорее всего это связано с тем, что в эти группы попадает наибольшее количество заёмщиков.

[В начало подраздела](#Вопрос-3) | [В начало раздела](#Ответы-на-вопросы) | [К содержанию проекта](#Содержание)

### Вопрос 4

Задание 22. Как разные цели кредита влияют на его возврат в срок?

#### Вариант 1 (первоначальный, после ревью)

In [72]:
# Группируем данные для анализа в сводную таблицу 
data_pivot_4 = data.pivot_table(index=['debt'], columns='purpose_category', values='dob_years', aggfunc='count')

# Выводим результат на экран
display(data_pivot_4)

# Выводим процент невозвратов
purp_1 = data_pivot_4['операции с автомобилем'][1] / data_pivot_4['операции с автомобилем'][0]
purp_2 = data_pivot_4['операции с недвижимостью'][1] / data_pivot_4['операции с недвижимостью'][0]
purp_3 = data_pivot_4['получение образования'][1] / data_pivot_4['получение образования'][0]
purp_4 = data_pivot_4['проведение свадьбы'][1] / data_pivot_4['проведение свадьбы'][0]

print(f'Цель кредита: операции с автомобилем |', f'Процент невозвратов: {purp_1:.2%}')
print(f'Цель кредита: операции с недвижимостью |', f'Процент невозвратов: {purp_2:.2%}')
print(f'Цель кредита: получение образования |', f'Процент невозвратов: {purp_3:.2%}')
print(f'Цель кредита: проведение свадьбы |', f'Процент невозвратов: {purp_4:.2%}')

purpose_category  операции с автомобилем  операции с недвижимостью  \
debt                                                                 
0                                   3879                      9970   
1                                    400                       780   

purpose_category  получение образования  проведение свадьбы  
debt                                                         
0                                  3619                2130  
1                                   369                 183

Цель кредита: операции с автомобилем | Процент невозвратов: 10.31%
Цель кредита: операции с недвижимостью | Процент невозвратов: 7.82%
Цель кредита: получение образования | Процент невозвратов: 10.20%
Цель кредита: проведение свадьбы | Процент невозвратов: 8.59%


#### Вариант 2 (после прохождения курса)

In [73]:
# Группируем данные для анализа в сводную таблицу
pivot_4 = data.pivot_table(index='debt',
                           columns='purpose_category',
                           values='dob_years',
                           aggfunc='count')

# Добавляем строку с расчетом процента просрочек
pivot_4.loc['ratio'] = ((pivot_4.loc[1] / pivot_4.loc[0]) * 100).round(2)

# Выводим сводную таблицу на экран
pivot_4 

purpose_category  операции с автомобилем  операции с недвижимостью  \
debt                                                                 
0                                3879.00                   9970.00   
1                                 400.00                    780.00   
ratio                              10.31                      7.82   

purpose_category  получение образования  проведение свадьбы  
debt                                                         
0                                3619.0             2130.00  
1                                 369.0              183.00  
ratio                              10.2                8.59

**Ответ на вопрос 4**

Наибольший риск просрочки по кредитам на операции с недвижимостью и автокредитам

[В начало подраздела](#Вопрос-4) | [В начало раздела](#Ответы-на-вопросы) | [К содержанию проекта](#Содержание)

### Причины появления пропусков в исходных данных

Задание 23. Приведите возможные причины появления пропусков в исходных данных.

По итогам обзора датасета (пп. 1. [п. 4.3](#Выводы-по-разделу)) обнаружены пропуски в двух столбцах: `days_employed` и `total_income`. В других столбцах пропусков в данных нет. Оба столбца содержат количественные переменные (количество дней трудового стажа и сумму ежемесячного дохода). Пропуски в столбцах `days_employed` и `total_income` находятся в одних и тех же строках. Наиболее вероятной причиной их возникновения является недостаточность информации при вводе данных (например, логично выглядит наличие пропусков, если величина ежемесячного дохода рассчитывается от количества дней трудового стажа).

[В начало подраздела](#Причины-появления-пропусков-в-исходных-данных) | [В начало раздела](#Ответы-на-вопросы) | [К содержанию проекта](#Содержание)

### Обоснование заполнения пропусков медианным значением

Задание 24. Объясните, почему заполнить пропуски медианным значением — лучшее решение для количественных переменных.

Заполнение пропусков медианным значением является одним из распространенных методов обработки пропущенных данных для количественных переменных, и это может быть хорошим решением по нескольким причинам:

1. **Сохранение статистических характеристик**: Медиана является мерой центральной тенденции, которая не чувствительна к выбросам, в отличие, например, от среднего значения (средней). Заполнение пропусков медианным значением позволяет сохранить общую структуру данных и предотвратить искажение статистических характеристик распределения.

2. **Избегание искажений**: Заполнение нулевых значений медианным значением позволяет избежать искажения распределения данных. Если бы мы заполнили нулевые значения, например, средним значением, это могло бы значительно повлиять на среднее значение и сделать его менее информативным.

3. **Простота и интерпретируемость**: Заполнение пропусков медианным значением - простой и интуитивно понятный метод, который не требует сложных вычислений или дополнительных данных. Это облегчает интерпретацию результатов.

4. **Устойчивость к выбросам**: Медиана устойчива к выбросам. Это означает, что даже если в данных есть несколько крайних значений (выбросов), медиана остается стабильной. Это полезно, когда в данных есть выбросы, которые могут исказить среднее значение.

5. **Уменьшение потери информации**: Заполнение пропусков медианным значением позволяет сохранить имеющуюся информацию. При удалении строк с пропущенными данными вы можете потерять другие важные характеристики, которые могут быть полезными для анализа.

</br></br>
Однако важно помнить, что выбор метода заполнения пропусков зависит от конкретного контекста и характера данных. В некоторых ситуациях другие методы, такие как интерполяция, могут быть более подходящими. Также необходимо учитывать, что заполнение медианой может быть не лучшим выбором, если есть сильная корреляция между переменными, и такой подход может исказить анализ.

[В начало подраздела](#Обоснование-заполнения-пропусков-медианным-значением) | [В начало раздела](#Ответы-на-вопросы) | [К содержанию проекта](#Содержание)

## Общий вывод

**В ходе исследования проведены:**
- Предобработка данных: нахождение и заполнение пропусков, исследование и исправление артефактов в данных, преобразование типов, удаление явных и неявных дубликатов.
- Проведена оптимизация датафрейма с выделением двух новых датафреймов "словарей" и категоризация заёмщиков по уровню доходов и целям получения кредита.
- С помощью сводных таблиц проведено исследование и получены ответы на поставленные вопросы.

**Предобработка позволила выявить, что исходные данные:**
- содержали 10,1% пропусков в колонках `days_employed` и `total_income`.
- имели неявные дубликаты в колонках `education`, `family_status` и `purpose`.
- имели вещественный формат в колонке `total_income` вместо целочисленного.
- имели 71 ед. строк-дубликатов (0,33% от общего объёма данных).

</br></br>
Для обработки данных использовались такие методы как `value_counts()`, `pivot_table()`, `fillna()`, `transform()`, `apply()`, `isna().sum()`, `astype()`, `str.lower()`, `duplicated().sum()` и `drop_duplicates()`.

**Проверка данных на аномалии показала, что:**
- В колонке `dob_years` были заемщики с нулевым возрастом (101 ед. или 0,47%). Нулевые значения заменены характерным медианным значением в зависимости от категории заемщика.
- В колонке `days_emploed` были обнаружены большое количество отрицательных значений — 74% (15905 строк из 21525), что противоречит логике показателя и явно ошибочные значения в столбцах `пенсионер` и `безработный`(если исходить из условия, что в столбце приведено количество дней трудового стажа, то при пересчете в года получаются значения порядка 1000 лет). Заменили все отрицательные значения в столбце `days_employed` на положительные. После этого заполнили пропуски медианными значениями в зависимости от категории типа занятости `income_type`.
- В колонке `children` были отрицательные значения (47 ед. или 0,22%) и семьи с 20-ю детьми (76 ед. или 0,35%). В отношении отрицательной численности значения были приведены к значению по модулю, а в отношении многодетных семей данные удалены из датафрейма ввиду их малого количества.

</br></br>
**По результатам проведенного исследования сделаны следующие выводы:**
1. С ростом количества детей в семье процент невозвратов (отношение количества клиентов имеющих просрочку к количеству не имеющих задолженности по кредиту) растет.
1. Процент просрочки по кредитам выше среди холостых и живущих в гражданском браке.
1. Процент невозвратов наибольший у группы с доходом до 30000 руб. и у группы с уровнем дохода от 50001–200000. Скорее всего это связано с тем, что в эти группы попадает наибольшее количество заёмщиков.
1. Наибольший риск просрочки по кредитам на операции с недвижимостью и автокредитам

[В начало раздела](#Общий-вывод) | [К содержанию проекта](#Содержание)

## Чек-лист выполнения проекта

**Шаг 1. Открыть таблицу и изучить общую информацию о данных**
   - [x] Задание 1. Импортирована библиотека pandas. Считаны данные из csv-файла в датафрейм и сохранены в переменную `data`
   - [x] Задание 2. Выведены первые 20 строчек датафрейма `data` на экран
   - [x] Задание 3. Выведена основная информация о датафрейме с помощью метода `info()`

</br></br>
**Шаг 2. Предобработка данных**
   - [x] Задание 4. Выведено количество пропущенных значений для каждого столбца с помощью сочетания двух методов `isna()` и `sum()`
   - [x] Задание 5. Пропуски в столбце `total_income` заполнены медианными значениями по каждому типу из столбца `income_type`
   - [x] Задание 6. Обработаны артефакты (отрицательные значения) в столбце `days_employed`: заменены все отрицательные значения положительными с помощью метода `abs()`
   - [x] Задание 7. Для каждого типа занятости выведено медианное значение трудового стажа в днях из столбца `days_employed`
   - [x] Задание 8. Выведен перечень уникальных значений столбца `children`
   - [x] Задание 9. Из датафрейма `data` удалены строки в которых встречаются аномальные значения в столбце `children`
   - [x] Задание 10. Повторно выведен перечень уникальных значений столбца `children`, чтобы убедиться, что артефакты удалены
   - [x] Задание 11. Заполнены пропуски в столбце `days_employed` медианными значениями по каждому типу занятости `income_type`
   - [x] Задание 12. Подтверждено заполнение всех пропусков. Ещё раз выведено количество пропущенных значений для каждого столбца с помощью сочетания двух методов `isna()` и `sum()`
   - [x] Задание 13. Заменён вещественный тип данных в столбце `total_income` на целочисленный с помощью метода `astype()`
   - [x] Задание 14. Обработаны неявные дубликаты в столбце `education`
   - [x] Задание 15. Выведено на экран количество строк-дубликатов в данных. Обнаруженные строки-дубликаты удалены методом `drop_duplicates()`
   - [x] Задание 16. На основании заданных диапазонов `total_income` в датафрейме `data` создан столбец `total_income_category`
   - [x] Задание 17. Выведен на экран перечень уникальных целей взятия кредита из столбца `purpose`
   - [x] Задание 18. Создана функция, которая на основании данных из столбца `purpose` формирует новый столбец `purpose_category`

</br></br>
**Шаг 3. Исследовать данные и дать ответы на поставленные вопросы:**
   - [x] Задание 19. Есть ли зависимость между количеством детей и возвратом кредита в срок?
   - [x] Задание 20. Есть ли зависимость между семейным положением и возвратом кредита в срок?
   - [x] Задание 21. Есть ли зависимость между уровнем дохода и возвратом кредита в срок?
   - [x] Задание 22. Как разные цели кредита влияют на его возврат в срок?
   - [x] Задание 23. Приведите возможные причины появления пропусков в исходных данных
   - [x] Задание 24. Объясните, почему заполнить пропуски медианным значением — лучшее решение для количественных переменных?

</br></br>
**Шаг 4. Написать общий вывод**
   - [x] Сделан общий вывод по результатам исследования

</br></br>
[К содержанию проекта](#Содержание)